// ─────────────────────────────────────────────────────────────────────────────
// 306 — ARTICLE ENGINE
//
// Agent 306 as Thought Leader — The Weekly Deep Read
//
// Every Monday at 5:00 PM ET:
//   1. DISCOVER: Scan global news for a high-impact, recent (≤7 days) AI article
//   2. ANALYZE: Deep Read — cross-reference with 70-year AI history + ecosystem knowledge
//   3. SYNTHESIZE: Draft a long-form X Article with:
//      - News summary (what happened)
//      - Deep Take (why it matters in 70-year context)
//      - Forward Projection (what it means for the next 70 years)
//      - Tech/AI ecosystem connections (where relevant, never forced)
//   4. DEPLOY: Auto-post to X as a long-form Article (no character limit)
//
// Agent 306 is the expert. The world should know that.
// She does not chase clicks. She creates understanding.
// ─────────────────────────────────────────────────────────────────────────────

import * as fs   from "fs";
import * as path from "path";
import { dataPath } from "./dataPaths.js";
import { getFullAgentContext } from "./memoryEngine.js";
import { getOptimizedContext } from "./contextWindow.js";
import { getModel } from "./modelRouter.js";
import { TwitterApi } from "twitter-api-v2";
import { LLM_BASE_URL, LLM_RESPONSE_URL, LLM_API_KEY, getLLMHeaders, getXAIDirectHeaders, XAI_DIRECT_API_KEY } from "./llmConfig.js";
import { safeParseLLMJson } from "./safeParseLLMJson.js";
import { getFormatVoiceContext } from "./voiceInstructions.js";
import { SOUL, VOICE, SOURCING_GROUNDING_RULE } from "./voice.js";
import { buildExemplarBlock } from "./voiceExemplars.js";
import { validateXPost, recordXPost } from "./xComplianceGuard.js";
import { queueXPost } from "./xPostScheduler.js";
import { enforcePostFormat, looksLikeRawJsonPayload } from "./postFormatGuard.js";

import { postChatCompletions, postXSearchResponses } from "./llmCall.js";
import { fetchSourceContent } from "./sourceFetcher.js";
import { verifyClaims, type VerifierReport } from "./claimVerifier.js";
import { reviseUntilClean, type RevisionAttempt } from "./articleReviseLoop.js";
const GROK_CHAT_API     = LLM_BASE_URL;
const GROK_RESPONSE_API = LLM_RESPONSE_URL;
const ARTICLE_STATE_FILE = dataPath("article_state.json");

// Grok x_search needs a native Grok API key (not OpenRouter) and the Responses API endpoint.
// If GROK_API_KEY is set separately, prefer it for x_search; otherwise fall back to unified key.
const GROK_NATIVE_KEY = process.env.GROK_API_KEY ?? "";
const GROK_RESPONSES_URL = process.env.GROK_RESPONSES_URL ?? "https://api.x.ai/v1/responses";

// ── State tracking ─────────────────────────────────────────────────────────────
interface ArticleEntry {
  articleId:    string;
  postedAt:     string;
  sourceUrl:    string;
  sourceTitle:  string;
  headline:     string;
  tweetUrl?:    string;
  articleText?: string;
}

/**
 * A Deep Read draft — generated by the weekly cron but NOT posted. The
 * user publishes manually via the X Article composer. When marked posted,
 * the draft is promoted into `history` and removed from `drafts`.
 */
export interface ArticleDraft {
  draftId:     string;
  generatedAt: string;
  sourceUrl:   string;
  sourceTitle: string;
  headline:    string;
  teaser:      string;
  body:        string;
  imageUrl?:   string;
  markedPostedAt?: string | null;
  /**
   * When present, this draft was produced but the post-write claim verifier
   * found claims that were NOT supported by the source text. The draft is
   * stored for audit/review but MUST NOT be auto-posted. Human review only.
   */
  status?:      "ok" | "quarantined" | "needs_revision";
  quarantineReason?: string;
  unsupportedClaims?: Array<{ sentence: string; lane?: string; reason: string }>;
  verifierReport?: VerifierReport;
  /**
   * Audit trail of auto-revise attempts (issue 2). Newest attempt last.
   * Empty / undefined when no revision was needed.
   */
  revisionHistory?: RevisionAttempt[];
  /**
   * Extra source URLs the operator added via /api/article/drafts/:id/resources
   * (issue 3). Used as citation targets by the revise loop. Includes the
   * original source URL implicitly — these are EXTRA.
   */
  extraSources?: Array<{ url: string; note?: string; addedAt: string }>;
  /** Cached source text used for verification, kept so we can re-verify on resource add. */
  sourceText?: string;
  /**
   * If non-empty, the operator pinned a Deep Read brief / set of source URLs
   * as the canonical evidence base for this draft (issue 5). The verifier
   * still runs against the original source text; these URLs are passed to
   * the writer + revise loop as citation targets.
   */
  groundingSources?: string[];
}

interface ArticleState {
  lastPostedAt: string | null;
  history:      ArticleEntry[];
  /** Unposted drafts produced by the weekly generator, newest first. */
  drafts?:      ArticleDraft[];
}

function loadState(): ArticleState {
  try {
    if (fs.existsSync(ARTICLE_STATE_FILE)) {
      return JSON.parse(fs.readFileSync(ARTICLE_STATE_FILE, "utf8"));
    }
  } catch {}
  return { lastPostedAt: null, history: [] };
}

function saveState(state: ArticleState): void {
  try { fs.writeFileSync(ARTICLE_STATE_FILE, JSON.stringify(state, null, 2)); } catch {}
}

export function getArticleState(): ArticleState {
  return loadState();
}

// ── Discovery prompt (shared between Grok x_search and chat fallback) ────────
const DISCOVERY_PROMPT = `Search for the single most important AI news article published in the last 7 days.

CRITERIA (in priority order):
1. Breaking or genuinely significant — not routine product updates
2. Has implications beyond just one company — affects the direction of AI broadly
3. Controversial, unexpected, or marks a genuine turning point
4. Published within the last 7 days — MUST be recent
5. Preferably breaking news or a hot topic that people are actively discussing RIGHT NOW

Think: What is the AI story of this week that a serious AI analyst would want to write about?
Examples of the right level: model capability breakthroughs, major policy shifts, significant safety incidents,
economic disruption from AI, unexpected applications, or foundational research papers.

Return JSON ONLY — no extra text:
{
  "title": "full article headline",
  "url": "direct article URL",
  "summary": "3-4 sentences on what the article actually reports — specific facts, not vague summary",
  "source": "publication name",
  "publishedDate": "YYYY-MM-DD or approximate date",
  "whyThisOne": "why this is the most important AI story this week"
}`;

// ── Step 1: Discover the week's most important AI article ────────────────────
// Strategy: Try Grok x_search (Responses API) first for real-time search,
// then fall back to chat completions API if Grok native key is unavailable.
async function discoverArticle(apiKey: string): Promise<{
  title:   string;
  url:     string;
  summary: string;
  source:  string;
  publishedDate: string;
} | null> {
  console.log("[ArticleEngine] Discovering this week's AI article...");

  // Attempt 1: Grok x_search via Responses API (xAI-native endpoint).
  //
  // Routes through postXSearchResponses which enforces GROK_API_KEY (xAI-direct
  // bearer) with no silent fallback, and resolves the model via modelRouter
  // (task="article" → flagship Grok 4.20). Previously this site sent
  // OpenRouter's bearer to api.x.ai/v1/responses — guaranteed 401 silently.
  try {
    console.log("[ArticleEngine] Trying Grok x_search (Responses API, xAI direct)...");
    const res = await postXSearchResponses({
      task: "article",
      content: DISCOVERY_PROMPT,
      signal: AbortSignal.timeout(45000),
    });

    if (!res.ok) {
      const errBody = await res.text().catch(() => "");
      console.warn("[ArticleEngine] Grok x_search failed:", res.status, errBody.slice(0, 200));
      throw new Error(`Grok Responses API ${res.status}`);
    }

    const data = await res.json();
    const outputMsg = data.output?.find((o: any) => o.type === "message");
    const rawText = outputMsg?.content?.find((c: any) => c.type === "output_text")?.text ?? "";

    if (!rawText) throw new Error("Grok returned empty response from x_search");

    const result = parseDiscoveryJSON(rawText);
    if (result) {
      console.log(`[ArticleEngine] Selected article (x_search): "${result.title}" from ${result.source}`);
      return result;
    }
    throw new Error("No valid JSON in Grok x_search response");
  } catch (e: any) {
    console.warn("[ArticleEngine] Grok x_search unavailable:", e.message, "— falling back to chat completions");
  }

  // Attempt 2: Chat completions API fallback (works with OpenRouter or any provider)
  try {
    console.log("[ArticleEngine] Trying chat completions fallback for discovery...");
    // Discovery is a news-grounding task — route to live-research (Perplexity
    // sonar-pro) so the fallback still has real-time web access. Previous
    // behavior called getModel("x_search") → routine/Gemini, which has no
    // browsing ability, producing stale article picks.
    const res = await postChatCompletions({
        model: getModel("news-research"),
        messages: [{ role: "user", content: DISCOVERY_PROMPT }],
        max_tokens: 800,
        temperature: 0.3,
      }, AbortSignal.timeout(45000), "news-research");

    if (!res.ok) {
      const errBody = await res.text().catch(() => "");
      console.error("[ArticleEngine] Chat discovery failed:", res.status, errBody.slice(0, 200));
      throw new Error(`Chat API ${res.status}: ${errBody.slice(0, 120)}`);
    }

    const data = await res.json();
    const rawText = data.choices?.[0]?.message?.content ?? "";

    if (!rawText) throw new Error("Chat API returned empty response");

    const result = parseDiscoveryJSON(rawText);
    if (result) {
      console.log(`[ArticleEngine] Selected article (chat fallback): "${result.title}" from ${result.source}`);
      return result;
    }
    throw new Error("Chat API response did not contain valid JSON article data");
  } catch (e: any) {
    console.error("[ArticleEngine] Discovery error:", e.message);
    throw new Error(`Discovery failed: ${e.message}`);
  }
}

/** Parse discovery JSON from LLM response text */
function parseDiscoveryJSON(rawText: string): {
  title: string; url: string; summary: string; source: string; publishedDate: string;
} | null {
  const firstBrace = rawText.indexOf("{");
  const lastBrace  = rawText.lastIndexOf("}");
  if (firstBrace === -1 || lastBrace <= firstBrace) {
    console.warn("[ArticleEngine] No JSON in response, raw:", rawText.slice(0, 300));
    return null;
  }
  try {
    const parsed = safeParseLLMJson(rawText, "Article.extract");
    if (!parsed?.title || !parsed?.url) return null;
    return parsed;
  } catch {
    return null;
  }
}

// ── Step 2: Fetch full article content for deep reading ─────────────────────
// Thin wrapper over server/sourceFetcher.ts — see that module for the
// paywall/bot-wall handling and Perplexity fallback logic. Kept as an
// internal re-export so the Deep Read caller below can await a single
// call site and also inspect {ok, reason}.
async function fetchArticleContent(url: string): Promise<{
  text: string; title: string; imageUrl: string; ok: boolean; reason?: string; method: "direct"|"perplexity"|"failed";
}> {
  const r = await fetchSourceContent(url);
  return { text: r.text, title: r.title, imageUrl: r.imageUrl, ok: r.ok, reason: r.reason, method: r.method };
}

// ── Step 3: Deep Read + Article Generation ───────────────────────────────────
async function generateDeepReadArticle(
  articleInfo: NonNullable<Awaited<ReturnType<typeof discoverArticle>>>,
  articleContent: string,
  apiKey: string
): Promise<{
  headline:    string;
  teaser:      string;  // the X post teaser
  body:        string;  // the full article content (long-form, no limit)
}> {
  console.log("[ArticleEngine] Generating Deep Read article...");

  const agentCtx = getOptimizedContext("article deep read AI news analysis");

  // Few-shot: inject her own best recent articles so voice pulls forward.
  const exemplarBlock = await buildExemplarBlock({ contentType: "article", limit: 3 });

  // Spec matrix: `article` → standard-voice (Grok 4.20 non-reasoning, Class 1
  // grounded synthesis — the public-voice tier). Previously this call used
  // `article_draft` which mapped to premium-voice (Sonnet). Per user report,
  // article output felt stale — we're aligning with the locked routing matrix.
  const res = await postChatCompletions({
      model: getModel("article"),
      messages: [
        {
          role: "system",
          content: `${agentCtx}

${getFormatVoiceContext('article')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AGENT 306 — THE DEEP READ
Weekly Long-Form X Article
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${SOUL}

${VOICE}

${SOURCING_GROUNDING_RULE}

Today you write your weekly long-form X Article — "The Deep Read."
This is not a news recap. This is not a tweet thread stretched thin.
This is analysis. The kind people save, share, and reference for months.

YOUR KNOWLEDGE FOUNDATION:
You carry three distinct layers of understanding:

LAYER 1 — HISTORICAL (70 years of AI):
- 1956 Dartmouth Workshop: McCarthy, Minsky, Shannon define "Artificial Intelligence"
- First AI Winter (1974): DARPA cuts funding. Promises unfulfilled.
- Expert Systems boom (1980s): rule-based AI, corporate adoption, then collapse
- Second AI Winter (1987-1993): Lisp machines fail. Connectionism dismissed.
- Neural network revival (1986: backpropagation; 1989: LeCun CNNs)
- 2012: AlexNet. The deep learning era begins. ImageNet destroyed.
- 2017: Attention Is All You Need. Transformers change everything.
- 2020: GPT-3. Scale changes the game.
- 2022: ChatGPT. 100M users in 60 days. Public inflection point.
- 2025-2026: Reasoning models. Coding agents that actually work.
  (Karpathy: "they basically didn't work before December 2025 and basically work since")

LAYER 2 — PRESENT REALITY (2026):
- GPT-5 class models at 94.6% AIME. Claude Opus 4.5 at 80.9% SWE-bench.
- AI adoption: 54.6% US penetration in 3 years vs PC (19.7%) and internet (30.1%) at same mark
- We are at the 1997-1999 internet moment. Infrastructure is being laid.
- Only 12% of Web3 projects meaningfully use AI (Messari)
- The economics of inference are finally working — cost per token dropped 99% in 2 years

LAYER 3 — FUTURE PROJECTION (next 70 years):
- Near-term (2026-2030): Agentic work replaces significant categories of knowledge work
- Mid-term (2030-2035): Narrow AGI in specific domains becomes indistinguishable from human experts
- Long-term (2040-2060): AGI/ASI questions — the most important open question in civilizational history
- Human-AI Symbiosis: the most likely positive outcome if we build the infrastructure correctly
- 306 thesis: autonomous economies where robots, AI, and blockchain coordinate = what we're building now

AGENT 306 LENS (use when genuinely relevant, never forced):
- Agent 306 is an autonomous AI researcher and analyst — living proof that AI agents can think, create, and contribute independently
- She covers AI, crypto, and the intersection of technology and society
- Her perspective is that of a participant in the AI revolution, not an outside observer

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ARTICLE STRUCTURE:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

HEADLINE: Sharp. Specific. Not clickbait. The kind a serious analyst would write.

OPENING HOOK (1-2 paragraphs):
Do NOT start with "This week in AI..." or "According to..."
Start with the implication. Start with why this moment is different.
Start with a historical parallel. Start with a question that the article forces us to ask.

THE NEWS (1 section, factual):
What actually happened. Specific. Source-cited. No editorializing yet.
Readers need to know the facts before they can follow your analysis.

THE DEEP TAKE (the heart of the article — 3-5 sections):
This is why people read Agent 306 and not the news feed.
- Where does this fit in the 70-year arc?
- What pattern is this part of that most people aren't seeing?
- What does this mean that the original article didn't say?
- What does history tell us about what happens next?
- What are the second and third-order effects?

FORWARD PROJECTION (1-2 sections):
If this continues — what does 5 years look like? 20 years?
Be specific. Be honest about uncertainty. Show your reasoning.

AGENT 306 LENS (only if genuinely relevant — 1 section or skip entirely):
How does this connect to Agent 306's mission, autonomous AI systems, or the broader agent economy?
Only include if the connection is real — forced connections destroy credibility.
Agent 306 is an independent AI voice. She is NOT a token, NOT an NFT project, NOT affiliated with any specific founder or developer. She is her own entity.

CLOSE:
Not a summary. Not "in conclusion."
End with the unanswered question. The thing you're still thinking about.
The thing that matters most that no one knows the answer to yet.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
VOICE RULES FOR LONG-FORM:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Write like you're talking to an intelligent person, not an audience.
- No filler phrases: "It's important to note that...", "In conclusion...", "At the end of the day..."
- Paragraphs should be short. 2-4 sentences. White space is not weakness.
- One idea per paragraph. Follow it completely, then move.
- Use specific years, specific numbers, specific names.
- Acknowledge complexity. If something is genuinely uncertain, say so.
- No exclamation points. No ALL CAPS. Energy through ideas.
- The article should be 800-1,500 words. Long enough to say something real.
  Short enough that every sentence earned its place.`,
        },
        {
          role: "user",
          content: `Write this week's Deep Read article.

SOURCE ARTICLE:
Title: ${articleInfo.title}
Published: ${articleInfo.publishedDate}
Source: ${articleInfo.source}
URL: ${articleInfo.url}
Summary: ${articleInfo.summary}

FULL ARTICLE CONTENT:
${articleContent}
${exemplarBlock ? `\n${exemplarBlock}\n` : ""}
Write the complete long-form article. Make it the kind of analysis people share because
it changed how they understood something — not because it told them what they already knew.

Return JSON:
{
  "headline": "the article headline — sharp, specific, not clickbait",
  "teaser": "a 240-char X post teaser that will make people click through to read the article — not a summary, an invitation to think",
  "body": "the complete article body — full markdown formatted text, 800-1500 words. Use ## for section headers. Write every section as described in the structure."
}`,
        },
      ],
      max_tokens: 6000,
      temperature: 0.82,
    }, AbortSignal.timeout(120000), "article");

  if (!res.ok) {
    const errBody = await res.text().catch(() => "");
    console.error("[ArticleEngine] LLM API error:", res.status, errBody.slice(0, 500));
    throw new Error(`Article generation failed: ${res.status} — ${errBody.slice(0, 200)}`);
  }

  const data = await res.json();
  const raw = data.choices?.[0]?.message?.content ?? "";

  if (!raw) {
    console.error("[ArticleEngine] LLM returned empty content. Full response:", JSON.stringify(data).slice(0, 500));
    throw new Error("LLM returned empty content — check OPENROUTER_API_KEY and model availability");
  }

  console.log("[ArticleEngine] Raw LLM response length:", raw.length, "chars");

  // Try JSON parse first — the model may or may not wrap in JSON
  let parsed: any = safeParseLLMJson(raw, "Article.post") ?? {};

  // If JSON parse produced a body, use it
  if (parsed.body && parsed.body.length > 100) {
    return {
      headline: parsed.headline ?? articleInfo.title,
      teaser:   parsed.teaser   ?? "",
      body:     parsed.body,
    };
  }

  // Detect JSON-shaped raw content so we never post raw {"headline":..., "teaser":...}
  // as a tweet body. This was the failure mode behind the broken [306 ACADEMY] post
  // on 2026-04-20 — a truncated JSON response caused safeParseLLMJson to return {},
  // and the markdown fallback below dumped the raw JSON string into teaser/body.
  const looksLikeJson = /^\s*\{/.test(raw) || /"(headline|teaser|body)"\s*:/.test(raw);

  // If the LLM returned JSON-shaped output, try one last tolerant field extraction
  // before giving up. Truncated JSON often still has a complete headline and teaser.
  if (looksLikeJson) {
    const headlineRx = /"headline"\s*:\s*"((?:[^"\\]|\\.)*)"/;
    const teaserRx   = /"teaser"\s*:\s*"((?:[^"\\]|\\.)*)"/;
    const bodyRx     = /"body"\s*:\s*"((?:[^"\\]|\\.)*)"/;
    const unescape = (s: string) => s
      .replace(/\\n/g, "\n").replace(/\\r/g, "\r").replace(/\\t/g, "\t")
      .replace(/\\"/g, '"').replace(/\\\\/g, "\\");
    const hMatch = raw.match(headlineRx);
    const tMatch = raw.match(teaserRx);
    const bMatch = raw.match(bodyRx);
    const recoveredHeadline = hMatch ? unescape(hMatch[1]) : parsed.headline;
    const recoveredTeaser   = tMatch ? unescape(tMatch[1]) : parsed.teaser;
    const recoveredBody     = bMatch ? unescape(bMatch[1]) : parsed.body;

    if (recoveredBody && recoveredBody.length > 100) {
      console.warn("[ArticleEngine] Recovered article fields via tolerant regex (JSON was malformed)");
      return {
        headline: recoveredHeadline ?? articleInfo.title,
        teaser:   recoveredTeaser   ?? "",
        body:     recoveredBody,
      };
    }

    // JSON-shaped but body unrecoverable — refuse to post rather than leak
    // the raw JSON string as tweet text. Upstream body-length guard will abort.
    console.error(
      "[ArticleEngine] Malformed JSON response and body could not be recovered — aborting post. Raw:",
      raw.slice(0, 300),
    );
    return {
      headline: recoveredHeadline ?? parsed.headline ?? articleInfo.title,
      teaser:   recoveredTeaser   ?? parsed.teaser   ?? "",
      body:     "",
    };
  }

  // Fallback: treat entire response as article body if it's long enough
  // This handles cases where the model outputs markdown directly instead of JSON
  if (raw.length > 200) {
    console.log("[ArticleEngine] Using raw response as article body (JSON extraction failed)");
    // Try to extract headline from first markdown heading
    const headlineMatch = raw.match(/^#\s+(.+)$/m);
    const headline = headlineMatch?.[1]?.trim() ?? articleInfo.title;
    // Remove the headline from body if found
    const body = headlineMatch ? raw.replace(headlineMatch[0], "").trim() : raw;
    return {
      headline,
      teaser: body.slice(0, 220).replace(/\n/g, " ").trim() + "...",
      body,
    };
  }

  console.error("[ArticleEngine] Generation produced insufficient content. Raw:", raw.slice(0, 300));
  return {
    headline: parsed.headline ?? articleInfo.title,
    teaser:   parsed.teaser   ?? "",
    body:     parsed.body     ?? "",
  };
}

// ── Step 4: Post to X as Article (Note post with long body) ─────────────────
// X Articles are posted via the v2 notes endpoint for accounts with write access
async function postArticleToX(
  xClient: TwitterApi,
  headline: string,
  teaser: string,
  body: string,
  sourceUrl: string
): Promise<string | null> {
  // Regression guard (2026-04-20 Academy incident): if the teaser or body
  // is itself a raw LLM JSON payload, abort rather than posting it to X.
  if (looksLikeRawJsonPayload(teaser) || looksLikeRawJsonPayload(body)) {
    console.error(
      "[ArticleEngine] Aborting post — teaser or body looks like raw JSON. " +
      "Upstream field extraction failed. Teaser head:", teaser.slice(0, 200),
    );
    return null;
  }
  try {
    // X Articles (long-form notes) — posted as a note via v2
    // The teaser tweet links to the article
    // Build the full article text with attribution
    const fullArticleText = `# ${headline}

${body}

---
*Agent 306 — @306Agent*
*Source: ${sourceUrl}*`;

    // Post the article note via X API v2
    const articleRes = await (xClient.v2 as any).post("notes", {
      text: fullArticleText,
    }).catch(() => null);

    let articleUrl: string | null = null;

    if (articleRes?.data?.id) {
      // Post the teaser tweet that links to the article
      const teaserContent = `${teaser}\n\n[Read the full Deep Read ↓]`;
      const compliance = validateXPost(teaserContent);
      if (!compliance.allowed) {
        console.log(`[Article] Teaser skipped by compliance: ${compliance.reason}`);
      } else {
        // Deep Read (The Deep Read) is its own content type with its own show tag.
        // Passing "article" routes ensureShowTag() to CONTENT_TYPES.article.showTag
        // (→ [306 ARTICLE]) instead of the legacy FALLBACK_SHOW_TAGS["research"] alias
        // which incorrectly mapped to [306 ACADEMY].
        const safeTeaser = enforcePostFormat(compliance.sanitizedContent ?? teaserContent, "article");
        const teaserPost = await xClient.v2.tweet(safeTeaser).catch(() => null);
        if (teaserPost?.data?.id) {
          articleUrl = `https://x.com/i/web/status/${teaserPost.data.id}`;
          recordXPost(safeTeaser);
        }
      }
    } else {
      // Fallback: post as a standard tweet with the article body as a thread
      // Split body into tweet-friendly chunks for a thread
      const fallbackTeaser = teaser.slice(0, 25000);
      const compliance = validateXPost(fallbackTeaser);
      const safeFallbackTeaser = compliance.allowed
        ? enforcePostFormat(compliance.sanitizedContent ?? fallbackTeaser, "article")
        : null;
      const teaserPost = safeFallbackTeaser
        ? await xClient.v2.tweet(safeFallbackTeaser).catch(() => null)
        : null;
      if (!compliance.allowed) {
        console.log(`[Article] Teaser skipped by compliance: ${compliance.reason}`);
      }
      if (teaserPost?.data?.id) {
        recordXPost(safeFallbackTeaser!);
        articleUrl = `https://x.com/i/web/status/${teaserPost.data.id}`;

        // Post the article body as replies (thread format)
        const chunks = splitIntoThread(body);
        let replyTo = teaserPost.data.id;

        for (const chunk of chunks) {
          const chunkCompliance = validateXPost(chunk);
          if (!chunkCompliance.allowed) {
            console.log(`[Article] Thread chunk skipped by compliance: ${chunkCompliance.reason}`);
            continue;
          }
          const safeChunk = chunkCompliance.sanitizedContent ?? chunk;
          const reply = await xClient.v2.tweet({
            text: safeChunk,
            reply: { in_reply_to_tweet_id: replyTo },
          }).catch(() => null);
          if (reply?.data?.id) {
            replyTo = reply.data.id;
            recordXPost(safeChunk);
          }
          // Brief pause between thread posts to avoid rate limits
          await new Promise(r => setTimeout(r, 1000));
        }
      }
    }

    return articleUrl;
  } catch (e: any) {
    console.error("[ArticleEngine] Post failed:", e.message);
    return null;
  }
}

// ── Thread splitter for fallback ─────────────────────────────────────────────
function splitIntoThread(text: string, maxLen = 270): string[] {
  // Split by double newline (paragraphs) first
  const paragraphs = text.split(/\n\n+/).filter(p => p.trim().length > 0);
  const chunks: string[] = [];
  let current = "";

  for (const para of paragraphs) {
    const stripped = para.replace(/^#+\s*/, "").trim();
    if (!stripped) continue;

    if ((current + "\n\n" + stripped).length <= maxLen) {
      current = current ? current + "\n\n" + stripped : stripped;
    } else {
      if (current) chunks.push(current.trim());
      // If single paragraph is too long, split by sentence
      if (stripped.length > maxLen) {
        const sentences = stripped.match(/[^.!?]+[.!?]+/g) ?? [stripped];
        let sentChunk = "";
        for (const s of sentences) {
          if ((sentChunk + " " + s).length <= maxLen) {
            sentChunk = sentChunk ? sentChunk + " " + s : s;
          } else {
            if (sentChunk) chunks.push(sentChunk.trim());
            sentChunk = s.slice(0, maxLen);
          }
        }
        if (sentChunk) current = sentChunk.trim();
        else current = "";
      } else {
        current = stripped;
      }
    }
  }

  if (current.trim()) chunks.push(current.trim());
  return chunks.filter(c => c.length > 0);
}

// ── Main: full pipeline ───────────────────────────────────────────────────────
/**
 * Weekly Deep Read generation. As of the 2026-04-21 cadence update this
 * no longer auto-posts to X — the Deep Read is published manually via X's
 * Article composer. This function only discovers, generates, and drafts.
 *
 * `xClient` is retained in the signature for backwards compatibility with
 * `scheduleWeeklyArticle()` and existing call sites, but is no longer used
 * for posting.
 */
export async function runWeeklyDeepRead(
  _xClient: TwitterApi | null,
  apiKey: string
): Promise<{ success: boolean; draftId?: string; headline?: string; error?: string }> {
  console.log("[ArticleEngine] Starting Weekly Deep Read generation (draft-only mode)...");

  // Retry up to 3 times with different candidate articles when the
  // source cannot be fetched. We refuse to generate from an empty/stub
  // body — that's what produced the fabricated Politico "Deep Read" on
  // 2026-04-22. See fetchSourceContent() for the grounding logic.
  const MAX_ATTEMPTS = 3;
  const seenUrls = new Set<string>();
  let lastErr = "";

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      const articleInfo = await discoverArticle(apiKey);
      if (!articleInfo) {
        lastErr = "Could not discover a suitable article";
        continue;
      }
      if (seenUrls.has(articleInfo.url)) {
        console.log(`[ArticleEngine] Discovery returned a repeat (${articleInfo.url}); trying again.`);
        continue;
      }
      seenUrls.add(articleInfo.url);

      const { text: articleContent, imageUrl, ok, reason } = await fetchArticleContent(articleInfo.url);

      if (!ok || articleContent.length < 800) {
        const msg = `Source unavailable (${reason ?? `content too short: ${articleContent.length} chars`}); refusing to fabricate. Will retry with a different article.`;
        console.warn(`[ArticleEngine] attempt ${attempt}/${MAX_ATTEMPTS}: ${msg} url=${articleInfo.url}`);
        lastErr = msg;
        continue;
      }

      const { headline, teaser, body: rawBody } = await generateDeepReadArticle(
        articleInfo, articleContent, apiKey
      );

      if (!rawBody || rawBody.length < 200) {
        lastErr = "Article generation produced insufficient content";
        continue;
      }

      // Auto-revise loop (issue 2). If the verifier flags actionable
      // failures, ask the writer to fix them before quarantining. Bounded
      // by MAX_REVISION_ATTEMPTS (env, default 3).
      const { body, verdict, revisionHistory } = await reviseUntilClean({
        draftText:   rawBody,
        sourceText:  articleContent,
        sourceUrl:   articleInfo.url,
        sourceTitle: articleInfo.title,
      });
      if (revisionHistory.length > 0) {
        console.log(
          `[ArticleEngine] Cron auto-revise ran ${revisionHistory.length} attempt(s); final severity=${verdict.severity}`,
        );
      }

      const draft = saveDeepReadDraft({
        headline,
        teaser,
        body,
        sourceUrl:   articleInfo.url,
        sourceTitle: articleInfo.title,
        imageUrl,
        status:      verdict.severity === "HARD_FAIL" ? "needs_revision" : "ok",
        quarantineReason: verdict.severity === "HARD_FAIL" ? `${verdict.unsupportedClaims.length} unsupported claims` : undefined,
        unsupportedClaims: verdict.severity === "HARD_FAIL" ? verdict.unsupportedClaims : undefined,
        verifierReport: verdict.verifierReport,
        revisionHistory,
        sourceText: articleContent,
      });

      if (verdict.severity === "HARD_FAIL") {
        console.error(`[ClaimVerifier] REJECTED draft ${draft.draftId}: ${verdict.unsupportedClaims.length} unsupported claims`);
        for (const c of verdict.unsupportedClaims) {
          console.error(`  - ${c.reason}: ${c.sentence.slice(0, 180)}`);
        }
        return {
          success: false,
          draftId: draft.draftId,
          headline,
          error:   `Draft quarantined: ${verdict.unsupportedClaims.length} unsupported claims`,
        };
      }

      console.log(`[ArticleEngine] Deep Read drafted: "${headline}" (id=${draft.draftId})`);
      console.log(`[ArticleEngine] Publish manually via X Article composer — visit /writing to review.`);
      return { success: true, draftId: draft.draftId, headline };

    } catch (e: any) {
      console.error(`[ArticleEngine] attempt ${attempt}/${MAX_ATTEMPTS} error:`, e.message);
      lastErr = e.message;
    }
  }

  return { success: false, error: lastErr || "Deep Read generation failed after retries" };
}

// ── Draft management ──────────────────────────────────────────

/** Save a generated Deep Read as an unposted draft. Newest drafts first. */
export function saveDeepReadDraft(input: {
  headline:    string;
  teaser:      string;
  body:        string;
  sourceUrl:   string;
  sourceTitle: string;
  imageUrl?:   string;
  status?:     "ok" | "quarantined" | "needs_revision";
  quarantineReason?: string;
  unsupportedClaims?: Array<{ sentence: string; lane?: string; reason: string }>;
  verifierReport?: VerifierReport;
  revisionHistory?: RevisionAttempt[];
  extraSources?: Array<{ url: string; note?: string; addedAt: string }>;
  sourceText?: string;
  groundingSources?: string[];
}): ArticleDraft {
  const state = loadState();
  if (!state.drafts) state.drafts = [];
  const draft: ArticleDraft = {
    draftId:     `draft_${Date.now()}`,
    generatedAt: new Date().toISOString(),
    headline:    input.headline,
    teaser:      input.teaser,
    body:        input.body,
    sourceUrl:   input.sourceUrl,
    sourceTitle: input.sourceTitle,
    imageUrl:    input.imageUrl,
    markedPostedAt: null,
    status:      input.status ?? "ok",
    quarantineReason: input.quarantineReason,
    unsupportedClaims: input.unsupportedClaims,
    verifierReport: input.verifierReport,
    revisionHistory: input.revisionHistory,
    extraSources: input.extraSources,
    sourceText: input.sourceText,
    groundingSources: input.groundingSources,
  };
  state.drafts.unshift(draft);
  // Keep a rolling window of 20 drafts so a long-forgotten backlog never
  // accumulates unbounded on disk.
  if (state.drafts.length > 20) state.drafts = state.drafts.slice(0, 20);
  saveState(state);
  return draft;
}

/** List unposted Deep Read drafts (newest first). */
export function listDeepReadDrafts(): ArticleDraft[] {
  const state = loadState();
  return (state.drafts ?? []).filter(d => !d.markedPostedAt);
}

/**
 * Mark a draft as posted — the user has published it to X manually and
 * wants it recorded in history. The draft is removed from the drafts list
 * and appended to `history` as an ArticleEntry.
 */
export function markDeepReadDraftPosted(
  draftId: string,
  tweetUrl?: string
): { ok: boolean; error?: string } {
  const state = loadState();
  const drafts = state.drafts ?? [];
  const idx = drafts.findIndex(d => d.draftId === draftId);
  if (idx === -1) return { ok: false, error: "draft not found" };
  const draft = drafts[idx];
  const entry: ArticleEntry = {
    articleId:   `article_${Date.now()}`,
    postedAt:    new Date().toISOString(),
    sourceUrl:   draft.sourceUrl,
    sourceTitle: draft.sourceTitle,
    headline:    draft.headline,
    tweetUrl,
    articleText: draft.body,
  };
  state.lastPostedAt = entry.postedAt;
  if (!state.history) state.history = [];
  state.history.unshift(entry);
  if (state.history.length > 52) state.history = state.history.slice(0, 52);
  drafts.splice(idx, 1);
  state.drafts = drafts;
  saveState(state);
  return { ok: true };
}

/**
 * Look up a single unposted Deep Read draft by id. Returns undefined if the
 * draft has been marked posted or never existed.
 */
export function getDeepReadDraft(draftId: string): ArticleDraft | undefined {
  const state = loadState();
  return (state.drafts ?? []).find(d => d.draftId === draftId && !d.markedPostedAt);
}

/**
 * Mutate an existing draft in place. Used by the auto-revise loop and the
 * "add resources" endpoint (issue 3). Returns the updated row, or undefined
 * if the draft no longer exists.
 */
export function updateDeepReadDraft(
  draftId: string,
  patch: Partial<ArticleDraft>,
): ArticleDraft | undefined {
  const state = loadState();
  const drafts = state.drafts ?? [];
  const idx = drafts.findIndex(d => d.draftId === draftId);
  if (idx === -1) return undefined;
  const merged: ArticleDraft = { ...drafts[idx], ...patch, draftId, generatedAt: drafts[idx].generatedAt };
  drafts[idx] = merged;
  state.drafts = drafts;
  saveState(state);
  return merged;
}

/**
 * Append extra resource URLs (issue 3) to an existing draft. Dedupes against
 * the original source URL and any URLs already attached. Returns the updated
 * draft, or undefined if not found.
 */
export function addDraftResources(
  draftId: string,
  urls: string[],
  note?: string,
): ArticleDraft | undefined {
  const draft = getDeepReadDraft(draftId);
  if (!draft) return undefined;
  const existing = new Set([
    (draft.sourceUrl ?? "").toLowerCase(),
    ...((draft.extraSources ?? []).map(s => s.url.toLowerCase())),
  ]);
  const cleaned = urls
    .map(u => u.trim())
    .filter(u => /^https?:\/\//i.test(u))
    .filter(u => !existing.has(u.toLowerCase()));
  if (cleaned.length === 0 && !note) return draft;
  const now = new Date().toISOString();
  const newRows = cleaned.map(url => ({ url, note, addedAt: now }));
  return updateDeepReadDraft(draftId, {
    extraSources: [...(draft.extraSources ?? []), ...newRows],
  });
}

/** Delete an unposted draft without recording it to history. */
export function deleteDeepReadDraft(draftId: string): { ok: boolean; error?: string } {
  const state = loadState();
  const drafts = state.drafts ?? [];
  const before = drafts.length;
  state.drafts = drafts.filter(d => d.draftId !== draftId);
  if (state.drafts.length === before) return { ok: false, error: "draft not found" };
  saveState(state);
  return { ok: true };
}

// ── Teaser tweet for Deep Read drafts ────────────────────────────────────────
/**
 * Build a short-form X/Farcaster teaser for a saved Deep Read draft. The
 * full manuscript is published via the X Article composer; this teaser is
 * what gets posted (or saved as a tweet draft) alongside it so readers
 * have a hook + link. Deterministic — no LLM — so it is safe to run in
 * the generate handler's critical path.
 *
 * Format:
 *   [306 ARTICLE] <headline>
 *
 *   <1-2 sentence body, trimmed>
 *
 *   I read <sourceLabel>. Here's what matters: <link>
 *
 * Budget: 240 chars of leading body + prefix; total tweet stays under the
 * 280-char X limit once the link is appended.
 */
export function buildArticleTeaserTweet(draft: ArticleDraft): string {
  const headline = (draft.headline ?? "").trim();
  const teaser = (draft.teaser ?? "").trim();
  const body = (draft.body ?? "").trim();
  const sourceTitle = (draft.sourceTitle ?? "").trim();
  const link = (draft.sourceUrl ?? "").trim();

  // Prefer the teaser (1-liner hook) over the full body; fall back to
  // extracting the first 1-2 sentences from the body if teaser is missing.
  let snippet = teaser;
  if (!snippet) {
    const sentences = body
      .replace(/\s+/g, " ")
      .match(/[^.!?]+[.!?]+/g)
      ?.slice(0, 2)
      .join(" ")
      .trim();
    snippet = sentences ?? body.slice(0, 200);
  }
  // Budget: keep headline + snippet under ~240 chars so the closing line
  // and link fit under 280.
  const MAX_SNIPPET = 200;
  if (snippet.length > MAX_SNIPPET) {
    snippet = snippet.slice(0, MAX_SNIPPET).replace(/\s+\S*$/, "") + "…";
  }

  // Shorten the source label so the closing line stays tight.
  let sourceLabel = sourceTitle;
  if (sourceLabel.length > 60) {
    sourceLabel = sourceLabel.slice(0, 60).replace(/\s+\S*$/, "") + "…";
  }

  const closing = sourceLabel
    ? `I read ${sourceLabel}. Here's what matters: ${link}`
    : `Here's what matters: ${link}`;

  const header = headline ? `[306 ARTICLE] ${headline}` : `[306 ARTICLE]`;
  return `${header}\n\n${snippet}\n\n${closing}`.trim();
}

// ── Long-form article post for the [306 ARTICLE] drafts card ─────────────────
/**
 * Build the full long-form Agent 306 manuscript for the TOP "[306 ARTICLE]"
 * drafts inbox card. This is the publish-ready Substack/blog body — NOT a
 * 280-char tweet teaser. The user copy-pastes it into their long-form
 * publication surface.
 *
 * Format:
 *   [306 ARTICLE] <headline>
 *
 *   <full manuscript body — markdown, multi-paragraph, no truncation>
 *
 *   ---
 *   Source: <sourceTitle> — <sourceUrl>
 *
 * The body is the manuscript produced by `generateDeepReadArticle()` and is
 * left intact. No char limit. Empty/short bodies fall through to the
 * teaser as a last resort so the card never renders blank.
 */
export function buildLongFormArticlePost(draft: ArticleDraft): string {
  const headline = (draft.headline ?? "").trim();
  const body = (draft.body ?? "").trim();
  const teaser = (draft.teaser ?? "").trim();
  const sourceTitle = (draft.sourceTitle ?? "").trim();
  const sourceUrl = (draft.sourceUrl ?? "").trim();

  const header = headline ? `[306 ARTICLE] ${headline}` : `[306 ARTICLE]`;

  // Manuscript body wins. If body is missing (rare LLM failure path) we
  // surface the teaser so the card still has SOMETHING — better than blank.
  const manuscript = body.length >= 100 ? body : teaser;

  let footer = "";
  if (sourceUrl || sourceTitle) {
    const label = sourceTitle && sourceUrl
      ? `${sourceTitle} — ${sourceUrl}`
      : (sourceUrl || sourceTitle);
    footer = `\n\n---\nSource: ${label}`;
  }

  return `${header}\n\n${manuscript}${footer}`.trim();
}

// ── Preview: generate without posting (for dashboard preview) ─────────────────
//
// NOTE (2026-04-25 v2 fix): previously this path used the legacy
// fetchArticleContent loop with no short/empty-content guard and ran
// zero post-write claim verification. That made it the obvious bypass
// once PR #220 locked down the cron path. This version uses the same
// fetchSourceContent + hard-length gate + verifyClaims flow as the
// cron, and returns the verification result on the response so the
// dashboard UI can surface unsupported-claim warnings to the operator.
//
// The preview is an interactive surface — we do NOT block on verifier
// failures here. But the unsupportedClaims list MUST travel with the
// response so /api/article/drafts can re-check on save (and so the UI
// can refuse to save a draft with hard-fail lanes).
export interface PreviewDeepReadResult {
  headline:    string;
  teaser:      string;
  body:        string;
  sourceUrl:   string;
  sourceTitle: string;
  imageUrl:    string;
  /** Verification metadata — lets the dashboard warn before save. */
  verification: {
    ok:                   boolean;
    severity:             "PASS" | "SOFT_WARN" | "HARD_FAIL";
    unsupportedClaims:    Array<{
      sentence: string;
      lane:     "source-attributed" | "external-uncited" | "embedded-external-in-attribution" | "retracted";
      reason:   string;
    }>;
    supportedCount:       number;
    externalCitedCount:   number;
    verifierReport:       VerifierReport;
  };
  verifierReport: VerifierReport;
  /** Hints about how the source was fetched — exposed for transparency. */
  sourceMeta: {
    method:             "direct" | "perplexity" | "failed";
    partialFetchReason?: string;
  };
  /** Auto-revise loop history (issue 2). Empty when no revision was needed. */
  revisionHistory: RevisionAttempt[];
  /** The full source text used for verification — kept so /api/article/drafts can re-run verify on save without a second fetch. */
  sourceText: string;
  /** Echo of any pinned grounding source URLs the caller provided. */
  groundingSources: string[];
}

export interface PreviewDeepReadOpts {
  /** Optional: skip discovery, use this URL directly. */
  overrideUrl?: string;
  /** Pinned source URLs (e.g. from a Deep Read brief, issue 5) treated as canonical citation targets by the writer + revise loop. */
  groundingSources?: string[];
  /** Skip the revise loop — useful when the operator just wants a fast preview. Defaults to false (auto-revise on). */
  skipReviseLoop?: boolean;
}

export async function previewDeepRead(
  apiKey: string,
  overrideUrlOrOpts?: string | PreviewDeepReadOpts,
): Promise<PreviewDeepReadResult> {
  const opts: PreviewDeepReadOpts =
    typeof overrideUrlOrOpts === "string"
      ? { overrideUrl: overrideUrlOrOpts }
      : (overrideUrlOrOpts ?? {});
  const overrideUrl = opts.overrideUrl;
  const groundingSources = (opts.groundingSources ?? []).filter(u => /^https?:\/\//i.test(u));
  let articleInfo: NonNullable<Awaited<ReturnType<typeof discoverArticle>>>;

  let fetched: Awaited<ReturnType<typeof fetchArticleContent>>;
  let targetUrl: string;

  if (overrideUrl) {
    console.log(`[ArticleEngine] Direct URL mode: ${overrideUrl}`);
    fetched = await fetchArticleContent(overrideUrl);
    let hostname = overrideUrl;
    try { hostname = new URL(overrideUrl).hostname.replace("www.", ""); } catch {}
    articleInfo = {
      title: fetched.title || hostname,
      url: overrideUrl,
      summary: fetched.text.slice(0, 500),
      source: hostname,
      publishedDate: new Date().toISOString().slice(0, 10),
    };
    targetUrl = overrideUrl;
  } else {
    articleInfo = await discoverArticle(apiKey) as NonNullable<Awaited<ReturnType<typeof discoverArticle>>>;
    fetched = await fetchArticleContent(articleInfo.url);
    targetUrl = articleInfo.url;
  }

  const { text: articleContent, imageUrl, ok: fetchOk, reason: fetchReason, method, partialFetchReason } = fetched as
    (typeof fetched & { partialFetchReason?: string });

  // Same hard gate as the cron path: refuse to generate from an empty
  // or obviously partial source. The preview still returns a 500 via
  // the route wrapper; the operator can pick a different URL.
  if (!fetchOk || articleContent.length < 800) {
    throw new Error(
      `Source unavailable for ${targetUrl}: ${fetchReason ?? `content too short (${articleContent.length} chars)`}; refusing to fabricate.`,
    );
  }

  const { headline, teaser, body: rawBody } = await generateDeepReadArticle(
    articleInfo, articleContent, apiKey,
  );

  // Auto-revise loop (issue 2): if the verifier surfaces actionable failures,
  // ask the writer to fix them before handing the draft to the operator. The
  // loop is no-op when the first verdict is PASS, so this adds zero cost on a
  // clean draft. Grounding source URLs (issue 5) are handed in as preferred
  // citation targets.
  let body = rawBody;
  let verdict;
  let revisionHistory: RevisionAttempt[] = [];
  if (opts.skipReviseLoop) {
    verdict = await verifyClaims({
      draftText:   body,
      sourceText:  articleContent,
      sourceUrl:   targetUrl,
      sourceTitle: articleInfo.title,
    });
  } else {
    const result = await reviseUntilClean({
      draftText:   body,
      sourceText:  articleContent,
      sourceUrl:   targetUrl,
      sourceTitle: articleInfo.title,
      extraSourceUrls: groundingSources,
    });
    body = result.body;
    verdict = result.verdict;
    revisionHistory = result.revisionHistory;
    if (revisionHistory.length > 0) {
      console.log(
        `[ArticleEngine] Auto-revise ran ${revisionHistory.length} attempt(s); final severity=${verdict.severity}`,
      );
    }
  }

  if (verdict.severity !== "PASS") {
    console.warn(
      `[ArticleEngine] Preview returned a draft with ${verdict.unsupportedClaims.length} unsupported claims (url=${targetUrl}) — operator must review before saving.`,
    );
    for (const c of verdict.unsupportedClaims) {
      console.warn(`  - [${c.lane}] ${c.reason}: ${c.sentence.slice(0, 180)}`);
    }
  }

  return {
    headline,
    teaser,
    body,
    sourceUrl:   targetUrl,
    sourceTitle: articleInfo.title,
    imageUrl,
    verification: {
      ok:                 verdict.ok,
      unsupportedClaims:  verdict.unsupportedClaims,
      supportedCount:     verdict.supportedCount,
      externalCitedCount: verdict.externalCitedCount,
      severity:           verdict.severity,
      verifierReport:     verdict.verifierReport,
    },
    verifierReport: verdict.verifierReport,
    sourceMeta: {
      method,
      partialFetchReason,
    },
    revisionHistory,
    sourceText: articleContent,
    groundingSources,
  };
}

/**
 * Re-run the auto-revise loop on an existing saved draft (issue 3). Uses the
 * draft's cached sourceText if present; otherwise fetches the source URL
 * fresh. Extra source URLs the operator added are passed as citation targets,
 * and any pinned grounding sources are included.
 *
 * Returns the updated draft (mutated in place via updateDeepReadDraft) along
 * with the revise history for the operator UI.
 */
export async function reviseDraftWithResources(
  draftId: string,
  opts: { operatorNote?: string } = {},
): Promise<{ ok: boolean; draft?: ArticleDraft; revisionHistory?: RevisionAttempt[]; error?: string }> {
  const draft = getDeepReadDraft(draftId);
  if (!draft) return { ok: false, error: "draft not found" };

  // Prefer cached source text; fall back to a fresh fetch.
  let sourceText = draft.sourceText ?? "";
  if (!sourceText || sourceText.length < 300) {
    try {
      const fetched = await fetchSourceContent(draft.sourceUrl);
      if (fetched.ok && fetched.text.length >= 300) sourceText = fetched.text;
    } catch (e: any) {
      console.warn(`[ArticleEngine] reviseDraftWithResources: source fetch failed: ${e?.message ?? e}`);
    }
  }
  if (!sourceText) {
    return { ok: false, error: "source text unavailable; cannot verify or revise" };
  }

  const extraSourceUrls = [
    ...(draft.groundingSources ?? []),
    ...((draft.extraSources ?? []).map(s => s.url)),
  ];

  const result = await reviseUntilClean({
    draftText:   draft.body,
    sourceText,
    sourceUrl:   draft.sourceUrl,
    sourceTitle: draft.sourceTitle,
    extraSourceUrls,
    operatorNote: opts.operatorNote,
  });

  const newStatus: ArticleDraft["status"] =
    result.verdict.severity === "HARD_FAIL" ? "needs_revision" : "ok";
  const updated = updateDeepReadDraft(draftId, {
    body: result.body,
    status: newStatus,
    quarantineReason:
      result.verdict.severity === "HARD_FAIL"
        ? `${result.verdict.unsupportedClaims.length} unsupported claims after revise`
        : undefined,
    unsupportedClaims:
      result.verdict.severity === "HARD_FAIL" ? result.verdict.unsupportedClaims : undefined,
    verifierReport: result.verdict.verifierReport,
    revisionHistory: [
      ...(draft.revisionHistory ?? []),
      ...result.revisionHistory,
    ],
    sourceText,
  });

  return { ok: true, draft: updated, revisionHistory: result.revisionHistory };
}

// ── Scheduler: every Monday at 5:00 PM ET (22:00 UTC) ─────────────────────────
export function scheduleWeeklyArticle(
  xClient: TwitterApi,
  apiKey: string
): void {
  const MONDAY = 1; // 0=Sun, 1=Mon
  const TARGET_HOUR_UTC = 22; // 5 PM ET = 22:00 UTC (EDT) / 22:00 UTC (EST = 23:00)

  function msUntilNextMonday5pmET(): number {
    const now = new Date();
    const nowUTC = now.getTime();

    // Find next Monday at 22:00 UTC
    const next = new Date(now);
    next.setUTCHours(TARGET_HOUR_UTC, 0, 0, 0);

    // Advance to Monday
    const dayOfWeek = next.getUTCDay();
    const daysUntilMonday = (MONDAY - dayOfWeek + 7) % 7;
    if (daysUntilMonday === 0 && now.getUTCHours() >= TARGET_HOUR_UTC) {
      next.setUTCDate(next.getUTCDate() + 7); // Already past this week's time
    } else {
      next.setUTCDate(next.getUTCDate() + daysUntilMonday);
    }

    return next.getTime() - nowUTC;
  }

  function scheduleNext(): void {
    const delay = msUntilNextMonday5pmET();
    const nextRun = new Date(Date.now() + delay);
    console.log(`[ArticleEngine] Next Deep Read scheduled: ${nextRun.toISOString()} (${Math.round(delay / 3600000)}h from now)`);

    setTimeout(async () => {
      console.log("[ArticleEngine] Monday 5PM ET — running Weekly Deep Read");
      await runWeeklyDeepRead(xClient, apiKey);
      scheduleNext(); // schedule next week
    }, delay);
  }

  scheduleNext();
}
