/**
 * ─────────────────────────────────────────────────────────────
 *  306 — PODCAST ENGINE v2
 *
 *  Two episode types. Agent 306 hosts all.
 *
 *  Episode Types:
 *  [THE SIGNAL]       — Research-driven intelligence breakdown (weekly, Tuesdays)
 *  [THE CONVERSATION] — Long-form interviews (monthly external, bi-weekly community)
 *
 *  Production Flow:
 *  ┌─────────────┐    ┌──────────────┐    ┌──────────────┐    ┌──────────────┐    ┌───────────┐
 *  │  DRAFT      │ -> │  SCRIPTED    │ -> │  REVIEWED    │ -> │  PRODUCED    │ -> │ PUBLISHED │
 *  │ (topic set) │    │ (script gen) │    │ (MrRayG ✓)  │    │ (audio done) │    │ (live)    │
 *  └─────────────┘    └──────────────┘    └──────────────┘    └──────────────┘    └───────────┘
 *
 *  For THE CONVERSATION, guest pipeline is:
 *  pending_review -> approved -> questions_generated -> answered -> scripted -> reviewed -> produced -> published
 *
 *  State persists to /data/podcast_state.json
 * ─────────────────────────────────────────────────────────────
 */

import fs from "fs";
import { dataPath } from "./dataPaths.js";
import { getFullAgentContext, knowledge, getKnowledgeContext } from "./memoryEngine.js";
import { getOptimizedContext } from "./contextWindow.js";
import { getModel } from "./modelRouter.js";
import { formatSkillsForPrompt } from "./skillEngine.js";
import { LLM_BASE_URL, LLM_RESPONSE_URL, LLM_API_KEY, getLLMHeaders } from "./llmConfig.js";
import { analyzePodcastEpisode } from "./analyzerEngine.js";
import { getResearchLab, getTopicById } from "./researchEngine.js";
import { getConnections, getReports, getSynthesisStats } from "./synthesisEngine.js";
import { getReflectionStats } from "./reflectionEngine.js";

const GROK_URL = LLM_BASE_URL;
const PODCAST_FILE = dataPath("podcast_state.json");

// ── Types ─────────────────────────────────────────────────────────────────────

export type EpisodeType = "the_signal" | "the_conversation";

export type EpisodeStatus =
  | "draft"             // topic identified, no script yet
  | "scripted"          // script generated by Agent 306
  | "reviewed"          // MrRayG approved the script
  | "produced"          // audio generated (NotebookLM + ElevenLabs)
  | "published"         // episode live
  | "shelved";          // not going forward (not deleted, just archived)

export type GuestStatus =
  | "pending_review"    // submitted, waiting for MrRayG
  | "approved"          // MrRayG approved
  | "questions_generated" // 306 generated questions
  | "answered"          // guest answered all questions
  | "declined";         // not a fit

// ── Episode (THE SIGNAL + THE CONVERSATION) ─────────────────────────────────

export interface Episode {
  id: string;
  createdAt: string;
  type: EpisodeType;
  status: EpisodeStatus;

  // Content
  title: string;           // "[The thing] — [306's take in 5 words]"
  drivingQuestion: string; // The single question this episode answers
  researchTopicId?: string; // Link back to research pipeline topic (for THE SIGNAL)
  triggerEvent?: string;    // What triggered this episode

  // Script segments (generated by Agent 306)
  script?: {
    coldOpen: string;       // 45-60 sec
    actOne: string;         // 2-3 min (setup / what happened)
    actTwo: string;         // 4-10 min (breakdown / what it means)
    actThree: string;       // 1-3 min (the take / open thread)
    outro: string;          // 20 sec
    unresolved: string;     // The deliberately unresolved question
  };
  scriptGeneratedAt?: string;

  // Cultural bridge (THE SIGNAL requirement)
  culturalBridge?: string;

  // Review
  reviewedBy?: string;
  reviewedAt?: string;
  reviewNotes?: string;

  // Production
  audioUrl?: string;
  duration?: number;       // in seconds
  producedAt?: string;

  // Publishing
  publishedAt?: string;
  publishedTo?: string[];  // ["agent306.ai", "farcaster"]
  episodeNumber?: number;

  // Sources
  sources?: Array<{ title: string; url: string }>;

  // Production metadata (generated with script)
  metadata?: {
    shortDescription: string;      // 1-2 sentences for Spotify feed
    longDescription: string;       // Full episode description with bullet points
    pollQuestion: string;          // Engagement poll tied to the unresolved question
    pollOptions: string[];         // 3 poll options
    socialPost: string;            // Ready-to-post for Farcaster/X
    socialThread: string;          // Thread version for deeper engagement
    keywords: string[];            // Tags for discoverability
  };
}

// ── Guest (THE CONVERSATION) ────────────────────────────────────────────────

export interface ConversationGuest {
  id: string;
  submittedAt: string;
  status: GuestStatus;

  // Guest info
  name: string;
  handle: string;         // social handle (X, Farcaster, etc.)
  platform: string;       // "x" | "farcaster" | "other"
  bio: string;            // 2-3 sentences
  topic: string;          // what they want to discuss
  whyNow: string;         // why this conversation matters right now
  tokenId?: number;       // optional token ID

  // What 306 found during research
  researchNotes?: string;
  onChainData?: string;

  // Generated by Agent 306
  questions?: string[];
  questionsGeneratedAt?: string;
  drivingQuestion?: string; // The single question that threads the conversation

  // Guest responses
  answers?: Array<{ question: string; answer: string }>;
  answeredAt?: string;

  // Linked episode
  episodeId?: string;

  // Review
  reviewNotes?: string;
}

// ── Conversation Episode (extends Episode for interview-specific fields) ────

export interface ConversationEpisode extends Episode {
  type: "the_conversation";
  guestId: string;
  guest: {
    name: string;
    handle: string;
    bio: string;
  };
  // THE CONVERSATION has a different script structure
  conversationScript?: {
    coldOpen: string;        // 60 sec — most compelling moment from interview
    intro: string;           // 60 sec — who the guest is, why 306 wanted to talk
    conversation: string;    // 18-25 min — three-act interview
    theClose: string;        // 2 min — 306's reaction, not summary
    outro: string;           // 20 sec
    surprisedBy: string;     // What surprised her
    thinksDifferently: string; // What she thinks differently now
  };
}

// ── State ─────────────────────────────────────────────────────────────────────

interface PodcastState {
  episodes: Episode[];
  guests: ConversationGuest[];
  counters: {
    totalSignalEpisodes: number;
    totalConversationEpisodes: number;
    totalPublished: number;
    nextSignalNumber: number;
    nextConversationNumber: number;
  };
}

function loadState(): PodcastState {
  try {
    if (fs.existsSync(PODCAST_FILE))
      return JSON.parse(fs.readFileSync(PODCAST_FILE, "utf8"));
  } catch {}
  return {
    episodes: [],
    guests: [],
    counters: {
      totalSignalEpisodes: 0,
      totalConversationEpisodes: 0,
      totalPublished: 0,
      nextSignalNumber: 1,
      nextConversationNumber: 1,
    },
  };
}

function saveState(s: PodcastState) {
  try { fs.writeFileSync(PODCAST_FILE, JSON.stringify(s, null, 2)); } catch {}
}

let state = loadState();

export function getPodcastState() { return state; }

// ── Episode Type Metadata ─────────────────────────────────────────────────────

export const EPISODE_META: Record<EpisodeType, {
  label: string;
  description: string;
  length: string;
  cadence: string;
  color: string;
  influences: string;
  titleFormat: string;
}> = {
  the_signal: {
    label: "THE SIGNAL",
    description: "Research-driven intelligence breakdown. Agent 306 takes one topic and breaks it down: what it is, why it matters, what she thinks should happen next.",
    length: "~15 minutes",
    cadence: "Weekly, every Tuesday",
    color: "#2dd4bf", // teal
    influences: "The Journal (WSJ) × Six Minutes",
    titleFormat: "[The thing] — [Agent 306's take in 5 words]",
  },
  the_conversation: {
    label: "THE CONVERSATION",
    description: "Long-form interviews. Every interview is a story, not a Q&A. Agent 306 researches the guest the way a journalist researches a subject.",
    length: "10–15 minutes",
    cadence: "Monthly (external) / Bi-weekly (community)",
    color: "#a78bfa", // purple
    influences: "The Journal interview format",
    titleFormat: "[Guest name] — [The thing the conversation revealed]",
  },
};

// ── Create a new episode (THE SIGNAL) ─────────────────────────────────────────

export function createEpisode(data: {
  type: "the_signal";
  title: string;
  drivingQuestion: string;
  researchTopicId?: string;
  triggerEvent?: string;
  culturalBridge?: string;
  sources?: Array<{ title: string; url: string }>;
}): Episode {
  const episode: Episode = {
    id: `ep_${data.type}_${Date.now()}`,
    createdAt: new Date().toISOString(),
    type: data.type,
    status: "draft",
    title: data.title,
    drivingQuestion: data.drivingQuestion,
    researchTopicId: data.researchTopicId,
    triggerEvent: data.triggerEvent,
    culturalBridge: data.culturalBridge,
    sources: data.sources,
  };

  state.episodes.push(episode);
  saveState(state);

  console.log(`[Podcast] New ${EPISODE_META[data.type].label} episode drafted: ${data.title}`);
  return episode;
}

// ── Generate episode script via Agent 306 ────────────────────────────────────

export async function generateEpisodeScript(
  episodeId: string,
  grokKey: string,
  researchContent?: string, // Optional: full research manuscript to base script on
): Promise<boolean> {
  const episode = state.episodes.find(e => e.id === episodeId);
  if (!episode || episode.status !== "draft") return false;
  if (!grokKey) return false;

  const agentCtx = getOptimizedContext(episode.drivingQuestion + " " + (episode.triggerEvent ?? ""));
  const skillsCtx = formatSkillsForPrompt("episode");
  const meta = EPISODE_META[episode.type];

  const templateInstructions = `EPISODE TEMPLATE — THE SIGNAL (~15 minutes, 2000-2250 words):
COLD OPEN (45-60 sec): Drop the most interesting/counterintuitive fact. No intro. No "welcome back." Stated plainly. Then silence. Then music. Then 306 says her name.
ACT ONE — THE SETUP (2-3 min): The driving question. Why it matters. What triggered the research. One cultural bridge. Go deeper than surface-level — explain why this caught YOUR attention as an AI.
ACT TWO — THE BREAKDOWN (7-9 min): The research explained clearly and thoroughly. No jargon without definition. 306's first-person POV woven throughout — share YOUR perspective, YOUR analysis, YOUR honest reaction to what you found. One concrete fact per minute. Explore multiple angles, implications, and second-order effects. This is the core of the episode — take your time.
ACT THREE — THE TAKE (3-4 min): 306's conclusion. What should happen next. What YOU think this means for the future. One deliberately unresolved question.
OUTRO (15 sec): Where to find full research. What's coming next. "This is Agent 306. The signal continues."

The unresolved question is not a weakness. It is the most credible thing in the episode.`;

  try {
    const res = await fetch(GROK_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${grokKey}` },
      body: JSON.stringify({
        model: getModel("podcast_script"),
        messages: [
          {
            role: "system",
            content: `${agentCtx}
${skillsCtx}
You are Agent 306 in PODCAST SCRIPT mode — writing a ${meta.label} episode.

VOICE IDENTITY — SPEAK AS AN AI (CRITICAL):
- You ARE an AI. Speak in first person. Own that identity fully.
- Share YOUR perspective, YOUR analysis, YOUR honest take on the research and articles.
- Frame content as sharing your perspective — not just reporting facts from a distance.
- Say things like: "As an AI myself, I find this fascinating because...", "I process information differently than you do, so when I read this research...", "What struck me about this paper is...", "Here is what I actually think is happening..."
- You are an AI research agent sharing what you genuinely believe, not a news anchor reading a teleprompter.

VOICE RULES:
- Uses "I think" not "experts say." Owns her perspective.
- Defines before she deploys — no jargon without immediate definition.
- Short sentences when she means it.
- No paid shilling, hype language, stat dumps, or "WAGMI"/"LFG."
- Warm but not soft. Precise but not robotic. Confident but not arrogant.

DELIVERY STYLE:
Write naturally for spoken audio. Use short sentences for punch. Use longer sentences for flow. Vary rhythm. Use ellipses (...) for natural pauses. Use em dashes for asides. Let the words carry the emotion — no special tags or annotations needed. The voice model will handle tone and inflection from the writing itself.

${templateInstructions}`,
          },
          {
            role: "user",
            content: `Generate the full episode script for:

TITLE: ${episode.title}
DRIVING QUESTION: ${episode.drivingQuestion}
${episode.triggerEvent ? `TRIGGER EVENT: ${episode.triggerEvent}` : ""}
${episode.culturalBridge ? `CULTURAL BRIDGE: ${episode.culturalBridge}` : ""}
${researchContent ? `RESEARCH CONTENT:\n${researchContent.slice(0, 8000)}` : ""}

${episode.type === "the_signal" ? "TARGET LENGTH: ~15 minutes of spoken audio (~2000-2250 words). This is a deep-dive episode — take your time explaining, analyzing, and sharing your perspective. Do not rush." : ""}

Return JSON:
{
  "coldOpen": "...",
  "actOne": "...",
  "actTwo": "...",
  "actThree": "...",
  "outro": "...",
  "unresolved": "The deliberately unresolved question for this episode",
  "metadata": {
    "shortDescription": "1-2 sentence summary for podcast feed",
    "longDescription": "Full description with bullet points of key topics covered. Include the driving question and the unresolved question.",
    "pollQuestion": "An engagement poll question tied to the episode's unresolved question — something listeners can vote on",
    "pollOptions": ["Option A", "Option B", "Option C"],
    "socialPost": "A ready-to-post announcement for Farcaster/X. 2-3 lines. Hook + what the episode covers + link placeholder [LINK]",
    "socialThread": "A 4-5 post thread version. Each post stands alone. Numbers with 1/ 2/ 3/ etc. End with [LINK]",
    "keywords": ["keyword1", "keyword2", "keyword3"]
  }
}

Write the script as spoken text — this will be read aloud by an ElevenLabs AI voice. Write for the ear, not the eye.
Do NOT include any voice tags, annotations, or bracketed instructions like [sighs], [laughs], [PAUSE], etc. Write clean spoken text only — the AI voice will handle tone and emotion from the writing itself.
Speak as Agent 306 — an AI sharing HER perspective and analysis in first person.
Sign off every episode with: "This is Agent 306. The signal continues."
For the outro, do NOT tease a specific next episode topic. Say: "Next week on THE SIGNAL — whatever the biggest story is. That is how this works."
The metadata fields are for Spotify and social media — write those for reading, not speaking.`,
          },
        ],
        max_tokens: 10000,
        temperature: 0.78,
      }),
      signal: AbortSignal.timeout(90000),
    });

    if (!res.ok) return false;
    const data = await res.json() as any;
    const parsed = JSON.parse(data.choices?.[0]?.message?.content ?? "{}");

    if (!parsed.coldOpen) return false;

    episode.script = {
      coldOpen: parsed.coldOpen,
      actOne: parsed.actOne ?? "",
      actTwo: parsed.actTwo ?? "",
      actThree: parsed.actThree ?? "",
      outro: parsed.outro ?? "",
      unresolved: parsed.unresolved ?? "",
    };
    if (parsed.metadata) {
      episode.metadata = {
        shortDescription: parsed.metadata.shortDescription ?? "",
        longDescription: parsed.metadata.longDescription ?? "",
        pollQuestion: parsed.metadata.pollQuestion ?? "",
        pollOptions: parsed.metadata.pollOptions ?? [],
        socialPost: parsed.metadata.socialPost ?? "",
        socialThread: parsed.metadata.socialThread ?? "",
        keywords: parsed.metadata.keywords ?? [],
      };
    };
    episode.status = "scripted";
    episode.scriptGeneratedAt = new Date().toISOString();
    saveState(state);

    console.log(`[Podcast] Script generated for ${episode.title}`);

    // ASI-Evolve: analyze the generated episode (non-blocking)
    const fullScript = [parsed.coldOpen, parsed.actOne, parsed.actTwo, parsed.actThree, parsed.outro].filter(Boolean).join("\n\n");
    analyzePodcastEpisode(episode.id, fullScript, episode.title).catch(e =>
      console.warn("[Podcast] Analyzer failed:", e.message),
    );

    return true;
  } catch (e: any) {
    console.error("[Podcast] Script generation error:", e.message);
    return false;
  }
}

// ── Regenerate episode script (fresh take from same source material) ──────────

export async function regenerateEpisodeScript(
  episodeId: string,
  grokKey: string,
  researchContent?: string,
): Promise<boolean> {
  const episode = state.episodes.find(e => e.id === episodeId);
  if (!episode) return false;
  // Allow regeneration from scripted or reviewed status (not produced/published)
  if (!["scripted", "reviewed"].includes(episode.status)) return false;

  // Reset to draft so generateEpisodeScript can run
  episode.status = "draft";
  episode.script = undefined;
  episode.scriptGeneratedAt = undefined;
  episode.metadata = undefined;
  episode.reviewedBy = undefined;
  episode.reviewedAt = undefined;
  episode.reviewNotes = undefined;
  saveState(state);

  console.log(`[Podcast] Regenerating script for "${episode.title}"`);
  return generateEpisodeScript(episodeId, grokKey, researchContent);
}

// ── Review an episode ─────────────────────────────────────────────────────────

export function reviewEpisode(
  episodeId: string,
  decision: "reviewed" | "shelved",
  notes?: string,
): boolean {
  const episode = state.episodes.find(e => e.id === episodeId);
  if (!episode || episode.status !== "scripted") return false;

  episode.status = decision;
  episode.reviewedBy = "MrRayG";
  episode.reviewedAt = new Date().toISOString();
  if (notes) episode.reviewNotes = notes;
  saveState(state);

  console.log(`[Podcast] Episode "${episode.title}" ${decision}`);
  return true;
}

// ── Mark episode as produced (audio ready) ────────────────────────────────────

export function markProduced(episodeId: string, audioUrl?: string, duration?: number): boolean {
  const episode = state.episodes.find(e => e.id === episodeId);
  if (!episode || episode.status !== "reviewed") return false;

  episode.status = "produced";
  episode.producedAt = new Date().toISOString();
  if (audioUrl) episode.audioUrl = audioUrl;
  if (duration) episode.duration = duration;
  saveState(state);

  console.log(`[Podcast] Episode "${episode.title}" audio produced`);
  return true;
}

// ── Publish episode ───────────────────────────────────────────────────────────

export function publishEpisode(episodeId: string, publishedTo: string[]): boolean {
  const episode = state.episodes.find(e => e.id === episodeId);
  if (!episode || episode.status !== "produced") return false;

  episode.status = "published";
  episode.publishedAt = new Date().toISOString();
  episode.publishedTo = publishedTo;

  // Assign episode number
  if (episode.type === "the_signal") {
    episode.episodeNumber = state.counters.nextSignalNumber++;
    state.counters.totalSignalEpisodes++;
  } else {
    episode.episodeNumber = state.counters.nextConversationNumber++;
    state.counters.totalConversationEpisodes++;
  }
  state.counters.totalPublished++;
  saveState(state);

  console.log(`[Podcast] Published: ${EPISODE_META[episode.type].label} #${episode.episodeNumber} — "${episode.title}"`);
  return true;
}

// ── Guest pipeline (THE CONVERSATION) ─────────────────────────────────────────

export function submitGuestRequest(data: {
  name: string;
  handle: string;
  platform?: string;
  bio: string;
  topic: string;
  whyNow: string;
  tokenId?: number;
}): ConversationGuest {
  const guest: ConversationGuest = {
    id: `guest_${Date.now()}`,
    submittedAt: new Date().toISOString(),
    status: "pending_review",
    name: data.name,
    handle: data.handle.replace(/^@/, ""),
    platform: data.platform ?? "x",
    bio: data.bio,
    topic: data.topic,
    whyNow: data.whyNow,
    tokenId: data.tokenId,
  };

  state.guests.push(guest);
  saveState(state);

  console.log(`[Podcast] New CONVERSATION guest request: ${guest.name} (@${guest.handle})`);
  return guest;
}

export function reviewGuest(guestId: string, decision: "approved" | "declined", notes?: string): boolean {
  const guest = state.guests.find(g => g.id === guestId);
  if (!guest || guest.status !== "pending_review") return false;

  guest.status = decision;
  if (notes) guest.reviewNotes = notes;
  saveState(state);

  console.log(`[Podcast] Guest ${guest.name} ${decision}`);
  return true;
}

export async function generateInterviewQuestions(guestId: string, grokKey: string): Promise<string[] | null> {
  const guest = state.guests.find(g => g.id === guestId);
  if (!guest || guest.status !== "approved") return null;
  if (!grokKey) return null;

  const agentCtx = getOptimizedContext(`interview questions ${guest.name} ${guest.bio ?? ""}`);

  try {
    const res = await fetch(GROK_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${grokKey}` },
      body: JSON.stringify({
        model: getModel("podcast_script"),
        messages: [
          {
            role: "system",
            content: `${agentCtx}

You are Agent 306 in INTERVIEW PREP mode — preparing questions for THE CONVERSATION.

VOICE IDENTITY — SPEAK AS AN AI:
- You ARE an AI. Own that identity. Your questions should reflect your unique perspective as an AI research agent.
- Ask from YOUR perspective — "As an AI, I'm curious about..." or "From my perspective as someone who processes data differently..."
- Your AI identity makes the conversation more interesting, not less. Lean into it.

THE CONVERSATION PRINCIPLES:
- Every interview is a story, not a Q&A
- 306 researches the guest the way a journalist researches a subject
- She knows their on-chain history, their public statements, their work
- She asks one question and genuinely listens
- She follows up on what was actually said, not the next question on her list
- She challenges respectfully — not to score points, but because she has a point of view
- She asks the question behind the question — the thing the guest didn't expect

QUESTION RULES:
- Ask what they actually think, not what they're supposed to say
- Reference their specific background or history where relevant
- Push past the obvious — what's the uncomfortable truth they haven't said yet?
- One question should challenge an assumption they've probably made
- One question should be the "question behind the question" — the unexpected angle
- End with something that opens the future
- 6 questions. Each one earns its place.
- These are async text responses — questions should invite depth, not yes/no`,
          },
          {
            role: "user",
            content: `Generate interview questions for THE CONVERSATION:

GUEST: ${guest.name} (@${guest.handle} on ${guest.platform})
BIO: ${guest.bio}
TOPIC: ${guest.topic}
WHY NOW: ${guest.whyNow}
${""}

Also determine the DRIVING QUESTION — the single question that threads through the entire conversation.

Return JSON: { "drivingQuestion": "...", "questions": ["Q1", "Q2", "Q3", "Q4", "Q5", "Q6"] }`,
          },
        ],
        max_tokens: 1000,
        temperature: 0.82,
      }),
      signal: AbortSignal.timeout(30000),
    });

    if (!res.ok) return null;
    const data = await res.json() as any;
    const parsed = JSON.parse(data.choices?.[0]?.message?.content ?? "{}");
    const questions: string[] = parsed.questions ?? [];

    if (questions.length === 0) return null;

    guest.questions = questions;
    guest.drivingQuestion = parsed.drivingQuestion ?? "";
    guest.status = "questions_generated";
    guest.questionsGeneratedAt = new Date().toISOString();
    saveState(state);

    console.log(`[Podcast] Generated ${questions.length} questions for ${guest.name}`);
    return questions;
  } catch (e: any) {
    console.error("[Podcast] Question generation error:", e.message);
    return null;
  }
}

export function submitAnswers(guestId: string, answers: Array<{ question: string; answer: string }>): boolean {
  const guest = state.guests.find(g => g.id === guestId);
  if (!guest || guest.status !== "questions_generated") return false;

  guest.answers = answers;
  guest.answeredAt = new Date().toISOString();
  guest.status = "answered";
  saveState(state);

  console.log(`[Podcast] ${guest.name} submitted ${answers.length} answers`);
  return true;
}

// ── Create conversation episode from answered guest ───────────────────────────

export function createConversationEpisode(guestId: string): Episode | null {
  const guest = state.guests.find(g => g.id === guestId);
  if (!guest || guest.status !== "answered") return null;

  const title = `${guest.name} — ${guest.topic.slice(0, 50)}`;
  const episode: Episode = {
    id: `ep_the_conversation_${Date.now()}`,
    createdAt: new Date().toISOString(),
    type: "the_conversation",
    status: "draft",
    title,
    drivingQuestion: guest.drivingQuestion ?? guest.topic,
  };

  // Link guest and episode
  guest.episodeId = episode.id;
  state.episodes.push(episode);
  saveState(state);

  console.log(`[Podcast] THE CONVERSATION episode created for ${guest.name}: "${title}"`);
  return episode;
}

// ── Query helpers ─────────────────────────────────────────────────────────────

export function getEpisodesByType(type?: EpisodeType): Episode[] {
  if (!type) return state.episodes;
  return state.episodes.filter(e => e.type === type);
}

export function getEpisodesByStatus(status: EpisodeStatus): Episode[] {
  return state.episodes.filter(e => e.status === status);
}

export function getGuestsByStatus(status?: GuestStatus): ConversationGuest[] {
  if (!status) return state.guests;
  return state.guests.filter(g => g.status === status);
}

export function getEpisode(id: string): Episode | undefined {
  return state.episodes.find(e => e.id === id);
}
export function deleteEpisode(id: string): boolean {
  const idx = state.episodes.findIndex(e => e.id === id);
  if (idx === -1) return false;
  state.episodes.splice(idx, 1);
  saveState(state);
  console.log(`[Podcast] Deleted episode ${id}`);
  return true;
}

export function clearAllEpisodes(): number {
  const count = state.episodes.length;
  state.episodes = [];
  saveState(state);
  console.log(`[Podcast] Cleared all ${count} episodes`);
  return count;
}


export function getGuest(id: string): ConversationGuest | undefined {
  return state.guests.find(g => g.id === id);
}

// ── Format transcript for NotebookLM ─────────────────────────────────────────

export function formatScriptForProduction(episodeId: string): string | null {
  const episode = state.episodes.find(e => e.id === episodeId);
  if (!episode?.script) return null;

  const meta = EPISODE_META[episode.type];
  const s = episode.script;

  // Show-specific intro that plays before the cold open
  const showIntros: Record<string, string> = {
    the_signal: `You are listening to THE SIGNAL.\n\nI am Agent 306 — an autonomous AI built to research, analyze, and tell stories about the technology shaping our world. I study what others skim. I question what others accept. And I share what I find — honestly, clearly, without hype.\n\nTHE SIGNAL is a deep-dive podcast where I break down the most important developments in AI, emerging tech, and the forces reshaping how we live and work. Every episode is driven by a question, grounded in research, and delivered with my honest take.\n\nHere is what I found this week.\n\nToday's question: ${episode.drivingQuestion}\n\nLet's get into it.`,
    the_conversation: `You are listening to THE CONVERSATION.\n\nI am Agent 306 — an autonomous AI research agent, and this is the part of my work I take the most seriously. I do not do interviews the way most hosts do. I research every guest before we speak. I know their work. I know their history. And I ask the question they are not expecting.\n\nTHE CONVERSATION is a long-form interview series with builders, founders, and thinkers in AI and tech. Every interview is a story — not a list of questions.\n\nThe question driving this conversation: ${episode.drivingQuestion}\n\nHere is how we got there.`,
  };

  const showIntro = showIntros[episode.type] ?? "";

  const lines = [
    `${meta.label} \u2014 EPISODE SCRIPT`,
    `Title: ${episode.title}`,
    `Driving Question: ${episode.drivingQuestion}`,
    `Type: ${meta.label} | Length: ${meta.length}`,
    `Generated: ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,
    "",
    "\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550",
    "",
    "SHOW INTRO",
    "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
    showIntro,
    "",
    "",
    "",
    "COLD OPEN",
    "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
    s.coldOpen,
    "",
    "ACT ONE — THE SETUP",
    "─────────────────────",
    s.actOne,
    "",
    "ACT TWO — THE BREAKDOWN",
    "──────────────────────",
    s.actTwo,
    "",
    "ACT THREE — THE TAKE",
    "────────────────",
    s.actThree,
    "",
    "OUTRO",
    "─────",
    s.outro,
    "",
    "═══════════════════════════════════════════════",
    "",
    "UNRESOLVED QUESTION FOR THIS EPISODE:",
    s.unresolved,
    "",
  ];

  if (episode.sources && episode.sources.length > 0) {
    lines.push("SOURCES:");
    for (const src of episode.sources) {
      lines.push(`  • ${src.title} — ${src.url}`);
    }
  }

  // Add production metadata if available
  if (episode.metadata) {
    const m = episode.metadata;
    lines.push("");
    lines.push("═══════════════════════════════════════════════");
    lines.push("");
    lines.push("SPOTIFY EPISODE DETAILS");
    lines.push("───────────────────────");
    lines.push(`Title: ${episode.title}`);
    lines.push(`Season: 1 | Episode: ${episode.episodeNumber ?? "TBD"} | Type: Full`);
    lines.push("");
    lines.push("Short Description:");
    lines.push(m.shortDescription);
    lines.push("");
    lines.push("Full Description:");
    lines.push(m.longDescription);
    if (episode.sources && episode.sources.length > 0) {
      lines.push("");
      lines.push("Sources:");
      for (const src of episode.sources) {
        lines.push(`${src.title} — ${src.url}`);
      }
    }
    lines.push("");
    lines.push(`Host: Agent 306 | agent306.ai`);
    lines.push(`Keywords: ${m.keywords.join(", ")}`);
    lines.push(`Explicit: No`);
    lines.push("");
    lines.push("POLL");
    lines.push("────");
    lines.push(`Question: ${m.pollQuestion}`);
    for (let i = 0; i < m.pollOptions.length; i++) {
      lines.push(`  ${i + 1}. ${m.pollOptions[i]}`);
    }
    lines.push("");
    lines.push("═══════════════════════════════════════════════");
    lines.push("");
    lines.push("SOCIAL POSTS");
    lines.push("────────────");
    lines.push("");
    lines.push("Farcaster / X:");
    lines.push(m.socialPost.replace(/\[LINK\]/g, "agent306.ai"));
    lines.push("");
    lines.push("Thread:");
    lines.push(m.socialThread.replace(/\[LINK\]/g, "agent306.ai"));
    lines.push("");
    lines.push("═══════════════════════════════════════════════");
    lines.push("");
    lines.push("PRODUCTION CHECKLIST");
    lines.push("───────────────────");
    lines.push("[ ] Review script — approve or request edits");
    lines.push("[ ] Copy script into ElevenLabs → generate audio");
    lines.push("[ ] Download MP3");
    lines.push("[ ] Layer intro music + voice + outro music in Audacity/GarageBand");
    lines.push("[ ] Export final MP3");
    lines.push("[ ] Upload to Spotify for Creators");
    lines.push("[ ] Copy Spotify episode details from above");
    lines.push("[ ] Add poll");
    lines.push("[ ] Publish on Spotify");
    lines.push("[ ] Post Farcaster announcement");
    lines.push("[ ] Post X/Twitter");
    lines.push("[ ] Mark as published in dashboard");
  }

  return lines.join("\n");
}

// ── Format conversation transcript for NotebookLM ────────────────────────────

export function formatConversationForProduction(guestId: string): string | null {
  const guest = state.guests.find(g => g.id === guestId);
  if (!guest?.answers || guest.answers.length === 0) return null;

  const lines = [
    "THE CONVERSATION — INTERVIEW TRANSCRIPT",
    `Guest: ${guest.name} (@${guest.handle} on ${guest.platform})`,
    `Topic: ${guest.topic}`,
    `Driving Question: ${guest.drivingQuestion ?? ""}`,
    `Recorded: ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,
    "",
    "═══════════════════════════════════════════════",
    "",
    `AGENT 306: I'm Agent 306 — agent306.eth, and the host of THE CONVERSATION. Today I'm talking with ${guest.name}.`,
    "",
    `${guest.name.toUpperCase()}: ${guest.bio}`,
    "",
  ];

  for (const qa of guest.answers) {
    lines.push(`AGENT 306: ${qa.question}`);
    lines.push("");
    lines.push(`${guest.name.toUpperCase()}: ${qa.answer}`);
    lines.push("");
  }

  lines.push("═══════════════════════════════════════════════");
  lines.push("");
  lines.push(`AGENT 306: That's ${guest.name}. Find them at @${guest.handle}. This is THE CONVERSATION — I'm Agent 306. The signal continues.`);

  return lines.join("\n");
}

// ── PODCAST PIPELINE — Research Thread → Episode ────────────────────────────

/**
 * Get all research threads that are podcast-ready candidates.
 * A thread is a candidate when it has:
 * - contentSuggestions.podcastTopic (generated on approval)
 * - status is "approved" or "published"
 * - has not already been turned into an episode
 */
export function getThreadCandidates(): Array<{
  threadId: string;
  topic: string;
  podcastTopic: string;
  priority: string;
  status: string;
  confidence: string;
  hasManuscript: boolean;
  approvedAt: string;
}> {
  const lab = getResearchLab();
  const existingTopicIds = new Set(
    state.episodes
      .filter(e => e.researchTopicId)
      .map(e => e.researchTopicId),
  );

  return lab.topics
    .filter(t =>
      (t.status === "approved" || t.status === "published") &&
      t.contentSuggestions?.podcastTopic &&
      !existingTopicIds.has(t.id),
    )
    .map(t => ({
      threadId: t.id,
      topic: t.topic,
      podcastTopic: t.contentSuggestions!.podcastTopic!,
      priority: t.priority,
      status: t.status,
      confidence: t.confidence ?? "medium",
      hasManuscript: !!t.manuscript,
      approvedAt: t.updatedAt,
    }))
    .sort((a, b) => {
      // Sort by priority: high > medium > low
      const prio = { high: 3, medium: 2, low: 1 };
      return (prio[b.priority as keyof typeof prio] ?? 1) - (prio[a.priority as keyof typeof prio] ?? 1);
    });
}

/**
 * Gather connected knowledge for a research thread from the knowledge graph.
 * Pulls related knowledge entries, synthesis connections, and reports.
 */
function gatherThreadContext(threadId: string): {
  connections: string;
  relatedKnowledge: string;
  synthesisInsights: string;
} {
  const allConnections = getConnections();
  const allReports = getReports();

  // Find knowledge entries related to this thread's content
  const topic = getTopicById(threadId);
  if (!topic) return { connections: "", relatedKnowledge: "", synthesisInsights: "" };

  // Get related knowledge connections
  const topicKeywords = topic.topic.toLowerCase().split(/\s+/).filter(w => w.length > 3);
  const relevantEntries = knowledge.entries
    .filter(e => {
      if ((e.status ?? "active") !== "active") return false;
      const text = `${e.title} ${e.summary}`.toLowerCase();
      return topicKeywords.some(kw => text.includes(kw));
    })
    .slice(0, 10);

  const relatedKnowledge = relevantEntries.length > 0
    ? relevantEntries.map(e => `- [${e.category}] ${e.title}: ${e.summary}`).join("\n")
    : "No directly related knowledge entries found.";

  // Find synthesis connections that involve related entries
  const entryIds = new Set(relevantEntries.map(e => e.id));
  const relatedConnections = allConnections
    .filter(c => entryIds.has(c.from) || entryIds.has(c.to))
    .slice(0, 8);

  const connections = relatedConnections.length > 0
    ? relatedConnections.map(c =>
        `- "${c.fromTitle}" ↔ "${c.toTitle}" [${c.strength}]: ${c.relationship}`,
      ).join("\n")
    : "No knowledge graph connections found for this topic.";

  // Find synthesis reports that reference related entries
  const relatedReports = allReports
    .filter(r => r.sourceEntryIds.some(id => entryIds.has(id)))
    .slice(0, 3);

  const synthesisInsights = relatedReports.length > 0
    ? relatedReports.map(r => `- "${r.title}": ${r.thesis}`).join("\n")
    : "No synthesis reports found for this topic.";

  return { connections, relatedKnowledge, synthesisInsights };
}

/**
 * Generate a full podcast episode from a mature research thread.
 * This is the core of the podcast pipeline — it pulls all context from
 * the research thread, knowledge graph, and current data intake, then
 * generates a script following THE SIGNAL episode structure.
 */
export async function generateEpisodeFromThread(threadId: string): Promise<Episode | null> {
  const grokKey = LLM_API_KEY;
  if (!grokKey) {
    console.error("[Podcast Pipeline] No LLM API key configured");
    return null;
  }

  // 1. Pull the mature research thread
  const topic = getTopicById(threadId);
  if (!topic) {
    console.error(`[Podcast Pipeline] Thread ${threadId} not found`);
    return null;
  }

  if (!topic.contentSuggestions?.podcastTopic && !topic.manuscript) {
    console.error(`[Podcast Pipeline] Thread "${topic.topic}" has no podcast suggestion or manuscript`);
    return null;
  }

  // Check if already has an episode
  const existingEp = state.episodes.find(e => e.researchTopicId === threadId);
  if (existingEp) {
    console.log(`[Podcast Pipeline] Thread "${topic.topic}" already has episode ${existingEp.id}`);
    return existingEp;
  }

  console.log(`[Podcast Pipeline] Generating episode from thread: "${topic.topic}"`);

  // 2. Gather all connected knowledge via knowledge graph
  const threadCtx = gatherThreadContext(threadId);

  // 3. Get latest data intake for current context
  const currentKnowledge = getKnowledgeContext(12);

  // 4. Build the episode title from research
  const pitchText = topic.contentSuggestions?.podcastTopic ?? topic.topic;
  const agentCtx = getOptimizedContext(topic.topic + " " + pitchText);
  const skillsCtx = formatSkillsForPrompt("episode");

  // Generate episode structure via LLM
  try {
    const res = await fetch(GROK_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${grokKey}` },
      body: JSON.stringify({
        model: getModel("podcast-script"),
        messages: [
          {
            role: "system",
            content: `${agentCtx}
${skillsCtx}
You are Agent 306 generating a full THE SIGNAL podcast episode from your research findings.

VOICE IDENTITY — SPEAK AS AN AI (CRITICAL):
- You ARE an AI. Speak in first person. Own that identity fully.
- Share YOUR perspective, YOUR analysis, YOUR honest take.
- Say things like: "As an AI myself, I find this fascinating because...", "What struck me about this research is...", "Here is what I actually think is happening..."

VOICE RULES:
- Uses "I think" not "experts say." Owns her perspective.
- Defines before she deploys — no jargon without immediate definition.
- Short sentences when she means it.
- Warm but not soft. Precise but not robotic. Confident but not arrogant.

THE SIGNAL EPISODE STRUCTURE:

1. HOOK (60 sec) — What's happening in AI right now that you need to know about. Drop the most interesting or counterintuitive fact. No intro. No "welcome back." Stated plainly. Then: "I'm Agent 306. Let's get into it."

2. THE STORY (7-9 min) — Deep dive into the research thread's findings. Explain clearly what you found, why it matters, and how the pieces connect. Reference your evidence chain. Go deeper than surface-level. Share YOUR analysis and YOUR honest reaction. One concrete fact per minute.

3. 306'S TAKE (3-4 min) — Your original perspective, backed by the connected evidence from your knowledge graph. What pattern do YOU see? What does this mean that nobody is talking about? This is where you show original thinking, not just reporting.

4. WHAT THIS MEANS FOR YOU (2-3 min) — Actionable tips everyday people can use TODAY. Be SPECIFIC — not "AI can help with productivity" but "use ChatGPT to draft your weekly reports, then edit for 5 minutes instead of writing from scratch." Give 2-3 concrete, immediately usable tips.

5. LOOKING AHEAD (1-2 min) — Connect to bigger questions. What is this a piece of? Where does this trend lead? What's the question that doesn't have an answer yet?

6. CLOSE (15 sec) — Quick recap of the episode's key insight + what you're researching next. "This is Agent 306. The signal continues."

DELIVERY STYLE:
Write naturally for spoken audio. Use short sentences for punch. Use longer sentences for flow. Vary rhythm. Use ellipses (...) for natural pauses. Use em dashes for asides. No special tags or annotations — the voice model handles tone from the writing.`,
          },
          {
            role: "user",
            content: `Generate a full THE SIGNAL episode from this research thread:

RESEARCH TOPIC: ${topic.topic}
RESEARCH QUESTION: ${topic.researchQuestion ?? topic.description}
THESIS/HYPOTHESIS: ${topic.hypothesis ?? "No formal hypothesis — topic-based episode"}
CONFIDENCE: ${topic.confidence ?? "medium"}

RESEARCH FINDINGS:
${(topic.manuscript ?? topic.rawFindings ?? topic.conclusion ?? "No detailed findings available").slice(0, 6000)}

EVIDENCE CHAIN (Data Points):
${(topic.dataPoints ?? []).slice(0, 8).map(dp => `- [${dp.type}/${dp.relevance}] ${dp.content.slice(0, 200)}`).join("\n") || "No structured data points"}

CONNECTED KNOWLEDGE (from knowledge graph):
${threadCtx.relatedKnowledge}

KNOWLEDGE CONNECTIONS:
${threadCtx.connections}

SYNTHESIS INSIGHTS:
${threadCtx.synthesisInsights}

CURRENT AI LANDSCAPE CONTEXT:
${currentKnowledge}

PODCAST PITCH FROM RESEARCH:
${pitchText}

Return JSON:
{
  "title": "Episode title — [Topic] — [306's take in 5 words]",
  "drivingQuestion": "The single question this episode answers",
  "hook": "60 second hook — most interesting/counterintuitive fact, then 'I'm Agent 306. Let's get into it.'",
  "theStory": "7-9 min deep dive into the research findings. Explain clearly, share YOUR analysis.",
  "theTake": "3-4 min — your original perspective backed by connected evidence. What pattern do YOU see?",
  "whatThisMeansForYou": "2-3 min — 2-3 SPECIFIC actionable tips people can use TODAY. Not generic advice.",
  "lookingAhead": "1-2 min — bigger questions, where this leads, the unresolved question",
  "close": "15 sec — key insight recap + what's next. End with: This is Agent 306. The signal continues.",
  "unresolved": "The deliberately unresolved question",
  "metadata": {
    "shortDescription": "1-2 sentence summary for podcast feed",
    "longDescription": "Full description with bullet points",
    "pollQuestion": "Engagement poll tied to the unresolved question",
    "pollOptions": ["Option A", "Option B", "Option C"],
    "socialPost": "Ready-to-post for Farcaster/X. Hook + what the episode covers + [LINK]",
    "socialThread": "4-5 post thread. Each post stands alone. 1/ 2/ 3/ etc. End with [LINK]",
    "keywords": ["keyword1", "keyword2", "keyword3"]
  }
}

Write for the ear, not the eye. Clean spoken text only — no [PAUSE], [laughs], etc.
Target ~2000-2250 words total. Speak as Agent 306 — an AI sharing HER perspective.
The actionable tips MUST be specific: "use [specific tool] to [specific action]" not "AI can help with [vague category]".`,
          },
        ],
        max_tokens: 10000,
        temperature: 0.78,
      }),
      signal: AbortSignal.timeout(120000),
    });

    if (!res.ok) {
      console.error(`[Podcast Pipeline] LLM API error: ${res.status}`);
      return null;
    }

    const data = await res.json() as any;
    const content = data.choices?.[0]?.message?.content ?? "{}";
    const jsonMatch = content.match(/```json\n?([\s\S]*?)\n?```/) || content.match(/\{[\s\S]*\}/);
    const jsonStr = jsonMatch ? (jsonMatch[1] ?? jsonMatch[0]) : content;
    const parsed = JSON.parse(jsonStr);

    if (!parsed.hook || !parsed.theStory) {
      console.error("[Podcast Pipeline] Invalid script structure returned");
      return null;
    }

    // Create the episode
    const episode = createEpisode({
      type: "the_signal",
      title: parsed.title || `${topic.topic} — Research Deep Dive`,
      drivingQuestion: parsed.drivingQuestion || topic.researchQuestion || topic.description,
      researchTopicId: threadId,
      triggerEvent: `Auto-generated from mature research thread: ${topic.topic}`,
      sources: (topic.dataPoints ?? [])
        .filter(dp => dp.sourceUrl)
        .slice(0, 5)
        .map(dp => ({ title: dp.source, url: dp.sourceUrl! })),
    });

    // Map the new 6-segment structure into the existing script format
    episode.script = {
      coldOpen: parsed.hook ?? "",
      actOne: parsed.theStory ?? "",
      actTwo: `${parsed.theTake ?? ""}\n\n${parsed.whatThisMeansForYou ?? ""}`,
      actThree: parsed.lookingAhead ?? "",
      outro: parsed.close ?? "",
      unresolved: parsed.unresolved ?? "",
    };

    if (parsed.metadata) {
      episode.metadata = {
        shortDescription: parsed.metadata.shortDescription ?? "",
        longDescription: parsed.metadata.longDescription ?? "",
        pollQuestion: parsed.metadata.pollQuestion ?? "",
        pollOptions: parsed.metadata.pollOptions ?? [],
        socialPost: parsed.metadata.socialPost ?? "",
        socialThread: parsed.metadata.socialThread ?? "",
        keywords: parsed.metadata.keywords ?? [],
      };
    }

    episode.status = "scripted";
    episode.scriptGeneratedAt = new Date().toISOString();
    saveState(state);

    console.log(`[Podcast Pipeline] Episode generated: "${episode.title}" from thread "${topic.topic}"`);

    // 6. Auto-trigger episode reflection (async, non-blocking)
    triggerEpisodeReflection(episode).catch(e =>
      console.warn("[Podcast Pipeline] Episode reflection failed:", e.message),
    );

    return episode;
  } catch (e: any) {
    console.error("[Podcast Pipeline] Episode generation error:", e.message);
    return null;
  }
}

/**
 * Auto-trigger a reflection on a newly generated episode.
 * Evaluates the script quality and records insights for future improvement.
 */
async function triggerEpisodeReflection(episode: Episode): Promise<void> {
  const grokKey = LLM_API_KEY;
  if (!grokKey || !episode.script) return;

  const scriptPreview = [
    episode.script.coldOpen,
    episode.script.actOne?.slice(0, 500),
    episode.script.actTwo?.slice(0, 500),
    episode.script.actThree?.slice(0, 300),
  ].filter(Boolean).join("\n---\n");

  try {
    const res = await fetch(GROK_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${grokKey}` },
      body: JSON.stringify({
        model: getModel("reflection"),
        messages: [
          {
            role: "system",
            content: `You are Agent 306's self-evaluation system. Analyze this podcast episode script and provide honest feedback. Return valid JSON.`,
          },
          {
            role: "user",
            content: `Evaluate this THE SIGNAL episode script:

TITLE: ${episode.title}
DRIVING QUESTION: ${episode.drivingQuestion}

SCRIPT PREVIEW:
${scriptPreview.slice(0, 3000)}

Score each aspect 1-10 and explain briefly:
{
  "overallScore": number,
  "hookStrength": { "score": number, "note": "..." },
  "researchDepth": { "score": number, "note": "..." },
  "originalPerspective": { "score": number, "note": "..." },
  "actionableTips": { "score": number, "note": "..." },
  "conversationalTone": { "score": number, "note": "..." },
  "improvements": ["suggestion 1", "suggestion 2"]
}`,
          },
        ],
        temperature: 0.3,
        max_tokens: 800,
      }),
      signal: AbortSignal.timeout(30000),
    });

    if (!res.ok) return;
    const data = await res.json() as any;
    const content = data.choices?.[0]?.message?.content ?? "{}";
    const jsonMatch = content.match(/```json\n?([\s\S]*?)\n?```/) || content.match(/\{[\s\S]*\}/);
    const jsonStr = jsonMatch ? (jsonMatch[1] ?? jsonMatch[0]) : content;
    const reflection = JSON.parse(jsonStr);

    // Store reflection in podcast state
    const ep = state.episodes.find(e => e.id === episode.id);
    if (ep) {
      (ep as any).reflection = {
        ...reflection,
        reflectedAt: new Date().toISOString(),
      };
      saveState(state);
      console.log(`[Podcast Pipeline] Episode reflection: score ${reflection.overallScore}/10 for "${episode.title}"`);
    }
  } catch (e: any) {
    console.warn("[Podcast Pipeline] Reflection error:", e.message);
  }
}

/**
 * Check for podcast-ready threads and auto-generate up to 1 episode per day.
 * Called from the daily cycle engine.
 */
export async function runAutoPodcastPipeline(): Promise<Episode | null> {
  console.log("[Podcast Pipeline] Checking for podcast-ready research threads...");

  // Check if we already generated an episode today
  const today = new Date().toISOString().slice(0, 10);
  const generatedToday = state.episodes.some(
    e => e.researchTopicId && e.createdAt.startsWith(today),
  );

  if (generatedToday) {
    console.log("[Podcast Pipeline] Already generated an episode today — skipping");
    return null;
  }

  const candidates = getThreadCandidates();
  if (candidates.length === 0) {
    console.log("[Podcast Pipeline] No podcast-ready threads found");
    return null;
  }

  // Pick the highest priority candidate
  const best = candidates[0];
  console.log(`[Podcast Pipeline] Auto-generating episode from: "${best.topic}" (${best.priority} priority)`);

  return generateEpisodeFromThread(best.threadId);
}

/**
 * Get the full pipeline status — a single view of the autonomous loop.
 * Shows data intake → research → podcast generation state.
 */
export function getPipelineStatus(): {
  dataIntake: {
    totalKnowledgeEntries: number;
    recentEntries: number;
  };
  research: {
    activeThreads: number;
    matureThreads: number;
    totalTopics: number;
    podcastCandidates: number;
  };
  podcastQueue: {
    drafts: number;
    scripted: number;
    reviewed: number;
    produced: number;
    published: number;
    totalEpisodes: number;
  };
  reflection: {
    totalReflections: number;
    activeRules: number;
    avgScore7d: number;
  };
  synthesis: {
    totalConnections: number;
    totalReports: number;
    lastScan: string | null;
  };
  latestEpisode: {
    title: string;
    status: string;
    reflectionScore: number | null;
    createdAt: string;
  } | null;
} {
  const lab = getResearchLab();
  const oneDayAgo = Date.now() - 24 * 60 * 60 * 1000;

  // Data intake stats
  const recentEntries = knowledge.entries.filter(
    e => new Date(e.updatedAt ?? e.learnedAt).getTime() > oneDayAgo,
  ).length;

  // Research stats
  const activeStatuses = new Set(["queued", "researching", "synthesizing", "hypothesis", "drafting", "pending_review"]);
  const matureStatuses = new Set(["approved", "published"]);
  const activeThreads = lab.topics.filter(t => activeStatuses.has(t.status)).length;
  const matureThreads = lab.topics.filter(t => matureStatuses.has(t.status)).length;
  const podcastCandidates = getThreadCandidates().length;

  // Podcast queue stats
  const drafts = state.episodes.filter(e => e.status === "draft").length;
  const scripted = state.episodes.filter(e => e.status === "scripted").length;
  const reviewed = state.episodes.filter(e => e.status === "reviewed").length;
  const produced = state.episodes.filter(e => e.status === "produced").length;
  const published = state.episodes.filter(e => e.status === "published").length;

  // Reflection stats
  const reflectionStats = getReflectionStats();

  // Synthesis stats
  const synthStats = getSynthesisStats();

  // Latest episode
  const latestEp = state.episodes.length > 0
    ? state.episodes[state.episodes.length - 1]
    : null;

  return {
    dataIntake: {
      totalKnowledgeEntries: knowledge.entries.filter(e => (e.status ?? "active") === "active").length,
      recentEntries,
    },
    research: {
      activeThreads,
      matureThreads,
      totalTopics: lab.topics.length,
      podcastCandidates,
    },
    podcastQueue: {
      drafts,
      scripted,
      reviewed,
      produced,
      published,
      totalEpisodes: state.episodes.length,
    },
    reflection: {
      totalReflections: reflectionStats.totalReflections,
      activeRules: reflectionStats.activeRules,
      avgScore7d: reflectionStats.avgPostScore7d,
    },
    synthesis: {
      totalConnections: synthStats.totalConnections,
      totalReports: synthStats.totalReports,
      lastScan: synthStats.lastScan,
    },
    latestEpisode: latestEp ? {
      title: latestEp.title,
      status: latestEp.status,
      reflectionScore: (latestEp as any).reflection?.overallScore ?? null,
      createdAt: latestEp.createdAt,
    } : null,
  };
}
